package com.sebu.backend.laboratoryreview.domain;

public enum LaboratoryReviewTag {

    RESEARCH_IMMERSION,
    STUDY_RESEARCH_BALANCE,
    FREE_ATMOSPHERE,
    STRUCTURED_RESEARCH_GUIDANCE,
    PROFESSOR_COMMUNICATION,
    ACTIVE_FEEDBACK,
    PROJECT_OPPORTUNITY,
    DIVERSE_RESEARCH_EXPERIENCE,
    INTEREST_FIELD_RESEARCH,
    CAREER_CONNECTION
}
