-- The classification table is a mapping reference only.
-- Do not create research fields that have not gone through the normal registration flow.
CREATE TEMPORARY TABLE tmp_research_field_category_seed (
    research_field_name VARCHAR(100) NOT NULL,
    category_code VARCHAR(50) NOT NULL,
    CONSTRAINT pk_tmp_research_field_category_seed
        PRIMARY KEY (research_field_name, category_code)
);

INSERT INTO tmp_research_field_category_seed (research_field_name, category_code)
VALUES
    ('3D', 'HCI_XR'),
    ('3D 오디오', 'SIGNAL_MEDIA'),
    ('3D Imaging System', 'PHOTONICS_OPTICS'),
    ('5G/6G 모바일 통신 및 센싱', 'COMM_NETWORK'),
    ('5G/6G 시스템', 'COMM_NETWORK'),
    ('6G 통신', 'COMM_NETWORK'),
    ('360 VR System', 'HCI_XR'),
    ('가상/증강/혼합현실', 'HCI_XR'),
    ('가상센서', 'CONTROL_SYSTEMS'),
    ('가상현실', 'HCI_XR'),
    ('가상화', 'SOFTWARE_COMPUTING'),
    ('가시광 통신', 'COMM_NETWORK'),
    ('감정인식', 'SIGNAL_MEDIA'),
    ('강인 제어', 'CONTROL_SYSTEMS'),
    ('강인 제어 및 외란 관측기', 'CONTROL_SYSTEMS'),
    ('강화학습', 'AI_ML'),
    ('강화학습기반 자율협력주행시스템', 'ROBOT_AUTONOMOUS'),
    ('거대 인공지능 모델', 'AI_ML'),
    ('검파및추정', 'CONTROL_SYSTEMS'),
    ('결정질 실리콘 태양전지', 'ENERGY_ENVIRONMENT'),
    ('결함 내성 시스템', 'SOFTWARE_COMPUTING'),
    ('경로 계획 및 장애물 회피', 'ROBOT_AUTONOMOUS'),
    ('고속 데이터센터 연결망 (high-speed data center interconnect, DCI)', 'COMM_NETWORK'),
    ('고속 디지털 시스템', 'SEMICONDUCTOR_HW'),
    ('고속 알고리즘', 'SIGNAL_MEDIA'),
    ('고장 감지 및 배제 알고리즘', 'CONTROL_SYSTEMS'),
    ('고장진단 및 수명예측', 'CONTROL_SYSTEMS'),
    ('공간 데이터 분석', 'DATA_INFORMATION'),
    ('공력·CFD 기반 성능최적화', 'INDUSTRIAL_MOBILITY'),
    ('공정 시스템 공학 (Process Systems Engineering)', 'CONTROL_SYSTEMS'),
    ('공중 관성항법 시스템', 'ROBOT_AUTONOMOUS'),
    ('공진기 및 필터', 'ELECTRONIC_DEVICES'),
    ('광대역통신', 'COMM_NETWORK'),
    ('광도파로', 'PHOTONICS_OPTICS'),
    ('광반도체 소자 반도체물리연구 미소링 공진기', 'PHOTONICS_OPTICS'),
    ('광반도체 소자 LED 및 응용 반도체 레이저 및 광 증폭기 소자 광통신 소자 및 시스템', 'PHOTONICS_OPTICS'),
    ('광섬유 광학 (fiber optics)', 'PHOTONICS_OPTICS'),
    ('광의료영상 시스템 및 적외선 무선충전', 'BIOMED_HEALTH'),
    ('구조 최적화 설계', 'CONTROL_SYSTEMS'),
    ('국방 정보 기술 사이버전 기슬 머신 러닝 유비쿼터스 멀티미디어 시스템', 'DEFENSE_MILITARY'),
    ('국방정책 및 전략', 'DEFENSE_MILITARY'),
    ('국제표준 비디오 코딩', 'SIGNAL_MEDIA'),
    ('군 지휘구조/부대구조/병력구조 등', 'DEFENSE_MILITARY'),
    ('궤도 추적', 'ROBOT_AUTONOMOUS'),
    ('그래프 신경망', 'AI_ML'),
    ('그래픽 하드웨어', 'SEMICONDUCTOR_HW'),
    ('금융 AI', 'POLICY_MANAGEMENT'),
    ('기계 학습', 'AI_ML'),
    ('기계/시스템 AI', 'CONTROL_SYSTEMS'),
    ('기계학습', 'AI_ML'),
    ('기계학습 기반 지능형 시스템 (스마트팩토리, 스마트시티, 디지털 트윈, 자율 · 엣지 AI)', 'AI_ML'),
    ('기능점수(Function Point)', 'SOFTWARE_COMPUTING'),
    ('기상 예측', 'ENERGY_ENVIRONMENT'),
    ('기후 빅데이터', 'ENERGY_ENVIRONMENT'),
    ('기후 정보학', 'ENERGY_ENVIRONMENT'),
    ('기후예측', 'ENERGY_ENVIRONMENT'),
    ('나노광학소자', 'PHOTONICS_OPTICS'),
    ('나노구조 설계·합성', 'ELECTRONIC_DEVICES'),
    ('나노소재: 2차원(2D) 소재(MXene, MoS2, 그래핀) 반도체 센서: 가스 센서', 'ELECTRONIC_DEVICES'),
    ('네트워크 보안', 'SECURITY_CRYPTO'),
    ('네트워크 제어 시스템', 'CONTROL_SYSTEMS'),
    ('다물체 동적 모델링', 'CONTROL_SYSTEMS'),
    ('다물체동역학의 대리모델링', 'CONTROL_SYSTEMS'),
    ('다중안테나 기술', 'COMM_NETWORK'),
    ('대규모 언어모델(LLM)', 'AI_ML'),
    ('대응', 'SECURITY_CRYPTO'),
    ('데이터 과학', 'DATA_INFORMATION'),
    ('데이터 기반 의사결정', 'DATA_INFORMATION'),
    ('데이터 마이닝 및 분석', 'DATA_INFORMATION'),
    ('데이터 및 보안 상호운용성', 'SECURITY_CRYPTO'),
    ('데이터 분석', 'DATA_INFORMATION'),
    ('데이터 사이언스', 'DATA_INFORMATION'),
    ('데이터 시각화', 'DATA_INFORMATION'),
    ('데이터 인텔리전스', 'DATA_INFORMATION'),
    ('데이터마이닝', 'DATA_INFORMATION'),
    ('데이터베이스', 'DATA_INFORMATION'),
    ('데이터분석', 'DATA_INFORMATION'),
    ('데이터사이언스', 'DATA_INFORMATION'),
    ('도시환경', 'ENERGY_ENVIRONMENT'),
    ('동영상 압축', 'SIGNAL_MEDIA'),
    ('드론 펌웨어 개발 및 알고리즘 구현', 'ROBOT_AUTONOMOUS'),
    ('드론 환경 인식', 'ROBOT_AUTONOMOUS'),
    ('디스플레이 화질 개선', 'SIGNAL_MEDIA'),
    ('디지털 영상 처리', 'SIGNAL_MEDIA'),
    ('디지털 영상 포렌직', 'SECURITY_CRYPTO'),
    ('디지털 통신 시스템', 'COMM_NETWORK'),
    ('디지털 트윈', 'INDUSTRIAL_MOBILITY'),
    ('디지털 TV', 'SIGNAL_MEDIA'),
    ('디지털신호처리', 'SIGNAL_MEDIA'),
    ('디지털콘텐츠 보안', 'SECURITY_CRYPTO'),
    ('디지털포렌식', 'SECURITY_CRYPTO'),
    ('딥 러닝', 'AI_ML'),
    ('딥러닝', 'AI_ML'),
    ('딥러닝기반 지능형교통시스템', 'INDUSTRIAL_MOBILITY'),
    ('레이다 및 라이다 신호처리', 'SIGNAL_MEDIA'),
    ('레이더 신호처리 배열 신호처리 통계 신호처리 해석적 성능분석 레이더 및 전자전 M&S 레이더 탐지 및 인식 알고리즘', 'DEFENSE_MILITARY'),
    ('레이저', 'PHOTONICS_OPTICS'),
    ('레이저광학 (laser optics)', 'PHOTONICS_OPTICS'),
    ('로보틱스', 'ROBOT_AUTONOMOUS'),
    ('로봇', 'ROBOT_AUTONOMOUS'),
    ('로봇 & 메커니즘 디자인', 'ROBOT_AUTONOMOUS'),
    ('로봇 제어/로봇 매니퓰레이터', 'ROBOT_AUTONOMOUS'),
    ('로봇 조작 및 작업 학습', 'ROBOT_AUTONOMOUS'),
    ('로봇공학', 'ROBOT_AUTONOMOUS'),
    ('로봇을 위한 인공지능 알고리즘', 'ROBOT_AUTONOMOUS'),
    ('리더십', 'DEFENSE_MILITARY'),
    ('마이크로 그리드', 'ENERGY_ENVIRONMENT'),
    ('마찰전기를 이용한 발전 소자', 'ENERGY_ENVIRONMENT'),
    ('머신 러닝', 'AI_ML'),
    ('머신러닝', 'AI_ML'),
    ('머신러닝&딥러닝', 'AI_ML'),
    ('멀티모달', 'AI_ML'),
    ('멀티모달 인공지능', 'AI_ML'),
    ('멀티모달 학습', 'AI_ML'),
    ('멀티모달 AI', 'AI_ML'),
    ('멀티모달LLM', 'AI_ML'),
    ('멀티미디어', 'SIGNAL_MEDIA'),
    ('멀티미디어 정보 처리', 'SIGNAL_MEDIA'),
    ('메타강화학습기반 차량경로안내시스템', 'INDUSTRIAL_MOBILITY'),
    ('메타물질 등을 이용한 무선채널 환경 제어', 'COMM_NETWORK'),
    ('메타버스', 'HCI_XR'),
    ('메타버스 보안', 'SECURITY_CRYPTO'),
    ('메타버스 시스템', 'HCI_XR'),
    ('모델링', 'CONTROL_SYSTEMS'),
    ('모바일 및 무선 시스템', 'COMM_NETWORK'),
    ('모빌리티 시스템 동역학 해석 및 제어', 'INDUSTRIAL_MOBILITY'),
    ('모션 아티팩트 보정', 'BIOMED_HEALTH'),
    ('모터 제어', 'CONTROL_SYSTEMS'),
    ('무선 네트워크', 'COMM_NETWORK'),
    ('무선 네트워크 및 엣지 컴퓨팅', 'COMM_NETWORK'),
    ('무선 이동통신', 'COMM_NETWORK'),
    ('무선 통신', 'COMM_NETWORK'),
    ('무선망 과 시스템 최적화', 'COMM_NETWORK'),
    ('무선통신', 'COMM_NETWORK'),
    ('무선통신 시스템', 'COMM_NETWORK'),
    ('무인 항공기(UAV)', 'ROBOT_AUTONOMOUS'),
    ('무인이동체 항법유도제어 센서 융합 및 자율주행항법 드론', 'ROBOT_AUTONOMOUS'),
    ('무인잠수정', 'ROBOT_AUTONOMOUS'),
    ('무인체계 및 지능로봇 분야 피지컬 AI 유무인복합체계 외', 'ROBOT_AUTONOMOUS'),
    ('문화기술(Culture Technology)', 'HCI_XR'),
    ('물류 체인 디지털 전환', 'INDUSTRIAL_MOBILITY'),
    ('물리계층 신호처리', 'COMM_NETWORK'),
    ('물리기반 인공지능', 'AI_ML'),
    ('물리적 AI(Embodied AI)', 'ROBOT_AUTONOMOUS'),
    ('물리정보 신경망', 'AI_ML'),
    ('물성/표면결함 제어', 'ELECTRONIC_DEVICES'),
    ('미디어 전송', 'COMM_NETWORK'),
    ('미소공진기', 'PHOTONICS_OPTICS'),
    ('미식최적화', 'BIOMED_HEALTH'),
    ('및 지도 작성 설명 가능한 강화학습', 'ROBOT_AUTONOMOUS'),
    ('및 퍼지 시스템', 'AI_ML'),
    ('바이오/의료 인공지능', 'BIOMED_HEALTH'),
    ('바이오로보틱스 생체 신호 인간-로봇 상호작용 웨어러블 로보틱스 원격 로봇 제어 시스템', 'ROBOT_AUTONOMOUS'),
    ('바이오메카닉스', 'BIOMED_HEALTH'),
    ('바이오메카트로닉스', 'BIOMED_HEALTH'),
    ('바이오센서', 'BIOMED_HEALTH'),
    ('바이오신호처리', 'BIOMED_HEALTH'),
    ('바이오인공지능', 'BIOMED_HEALTH'),
    ('반도체 공정', 'SEMICONDUCTOR_HW'),
    ('반도체 소자 및 공정', 'SEMICONDUCTOR_HW'),
    ('반도체 소자 및 소재 연구', 'SEMICONDUCTOR_HW'),
    ('반도체 소재', 'SEMICONDUCTOR_HW'),
    ('반도체 패키징', 'SEMICONDUCTOR_HW'),
    ('병렬 처리 등', 'SOFTWARE_COMPUTING'),
    ('보건 정보학', 'BIOMED_HEALTH'),
    ('보안공학', 'SECURITY_CRYPTO'),
    ('보행자 및 차량 객체 인식', 'ROBOT_AUTONOMOUS'),
    ('북한학', 'DEFENSE_MILITARY'),
    ('분산 알고리즘 및 미들웨어', 'SOFTWARE_COMPUTING'),
    ('분산/병렬 파일시스템 및 저장장치시스템', 'SOFTWARE_COMPUTING'),
    ('분산학습', 'AI_ML'),
    ('분석', 'DATA_INFORMATION'),
    ('불확실성 정량화', 'CONTROL_SYSTEMS'),
    ('불확실성 추정', 'CONTROL_SYSTEMS'),
    ('블록체인', 'SECURITY_CRYPTO'),
    ('블록체인 기반 에너지 시스템', 'ENERGY_ENVIRONMENT'),
    ('블록체인 프라이버시', 'SECURITY_CRYPTO'),
    ('비디오 코딩', 'SIGNAL_MEDIA'),
    ('비디오압축', 'SIGNAL_MEDIA'),
    ('비선형광학 (nonlinear optics)', 'PHOTONICS_OPTICS'),
    ('비정형 데이터 어노테이션', 'DATA_INFORMATION'),
    ('빅데이터', 'DATA_INFORMATION'),
    ('빅데이터 보안', 'SECURITY_CRYPTO'),
    ('사물인터넷', 'COMM_NETWORK'),
    ('사물인터넷 보안', 'SECURITY_CRYPTO'),
    ('사물인터넷(IoT)', 'COMM_NETWORK'),
    ('사용자 경험', 'HCI_XR'),
    ('사용자 경험(UX) 인공지능 머신러닝 딥러닝 자연어처리', 'HCI_XR'),
    ('사이버 물리 시스템의 안전성 및 보안', 'SECURITY_CRYPTO'),
    ('사이버 보안', 'SECURITY_CRYPTO'),
    ('사이버 지휘통제', 'DEFENSE_MILITARY'),
    ('사이버보안', 'SECURITY_CRYPTO'),
    ('사이버안보', 'SECURITY_CRYPTO'),
    ('사이버전 개론 사이버전자기 스팩트럼전 사이버전과 물리전의 결합', 'DEFENSE_MILITARY'),
    ('사이버전자 기술', 'SECURITY_CRYPTO'),
    ('산업 인공지능', 'INDUSTRIAL_MOBILITY'),
    ('산업 인공지능(AI)', 'INDUSTRIAL_MOBILITY'),
    ('산업 AI', 'INDUSTRIAL_MOBILITY'),
    ('산업인공지능', 'INDUSTRIAL_MOBILITY'),
    ('산화물 나노물질 및 박막 합성', 'ELECTRONIC_DEVICES'),
    ('상륙작전', 'DEFENSE_MILITARY'),
    ('상태 추정', 'CONTROL_SYSTEMS'),
    ('색역 사상', 'SIGNAL_MEDIA'),
    ('생성모델', 'AI_ML'),
    ('생성형AI', 'AI_ML'),
    ('생의학 영상', 'BIOMED_HEALTH'),
    ('생체삽입형 전자소자', 'BIOMED_HEALTH'),
    ('생체의학 신호 및 영상 처리', 'BIOMED_HEALTH'),
    ('선박 제어 알고리즘', 'ROBOT_AUTONOMOUS'),
    ('선박 충돌회피', 'ROBOT_AUTONOMOUS'),
    ('선형 및 비선형 제어', 'CONTROL_SYSTEMS'),
    ('설명 가능한 AI(XAI)', 'AI_ML'),
    ('성능분석', 'COMM_NETWORK'),
    ('성층권 HALE/HAPS', 'ROBOT_AUTONOMOUS'),
    ('센서 정보이론/ 보안', 'SECURITY_CRYPTO'),
    ('수중', 'ROBOT_AUTONOMOUS'),
    ('수중 차량 및 로봇', 'ROBOT_AUTONOMOUS'),
    ('수중무인체 등 무인이동체 임베디드시스템 탐지인식 및 AI 의사결정시스템', 'ROBOT_AUTONOMOUS'),
    ('수중음향', 'SIGNAL_MEDIA'),
    ('스마트 그리드', 'ENERGY_ENVIRONMENT'),
    ('스마트 그리드 최적화', 'ENERGY_ENVIRONMENT'),
    ('스마트 네트워크관리', 'COMM_NETWORK'),
    ('스마트 모빌리티', 'INDUSTRIAL_MOBILITY'),
    ('스마트 시티', 'INDUSTRIAL_MOBILITY'),
    ('스마트 팩토리', 'INDUSTRIAL_MOBILITY'),
    ('스마트시티', 'INDUSTRIAL_MOBILITY'),
    ('시각언어모델', 'AI_ML'),
    ('시각적 데이터 분석', 'DATA_INFORMATION'),
    ('시간 지연 시스템', 'CONTROL_SYSTEMS'),
    ('시계열 로봇 센서 데이터 처리를 위한 AI', 'ROBOT_AUTONOMOUS'),
    ('시계열 예측', 'AI_ML'),
    ('시뮬레이션 대리모델링', 'CONTROL_SYSTEMS'),
    ('시스템 보안', 'SECURITY_CRYPTO'),
    ('시스템 신뢰성 및 가용성', 'CONTROL_SYSTEMS'),
    ('시스템 제어', 'CONTROL_SYSTEMS'),
    ('시스템보안', 'SECURITY_CRYPTO'),
    ('신뢰성·안전·인증', 'INDUSTRIAL_MOBILITY'),
    ('신뢰할 수 있는 인공지능(Trustworthy AI)', 'AI_ML'),
    ('신재생 에너지', 'ENERGY_ENVIRONMENT'),
    ('신호/전력 무결성', 'SEMICONDUCTOR_HW'),
    ('신호처리', 'SIGNAL_MEDIA'),
    ('신호처리 기반 딥러닝', 'SIGNAL_MEDIA'),
    ('실시간 렌더링', 'HCI_XR'),
    ('심층 강화 학습', 'AI_ML'),
    ('심층 영상/라이다 위치추정 강화학습(XRL)', 'ROBOT_AUTONOMOUS'),
    ('아날로그 및 혼성신호 집적회로 설계', 'SEMICONDUCTOR_HW'),
    ('아날로그 VLSI 설계 혼성신호 IC 설계 FPD 구동', 'SEMICONDUCTOR_HW'),
    ('아날로그&디지털 혼성회로 설계', 'SEMICONDUCTOR_HW'),
    ('아연 이온 배터리(Zn-ion Battery)', 'ENERGY_ENVIRONMENT'),
    ('안티탬퍼링', 'SECURITY_CRYPTO'),
    ('암호', 'SECURITY_CRYPTO'),
    ('암호 프로토콜', 'SECURITY_CRYPTO'),
    ('암호학', 'SECURITY_CRYPTO'),
    ('양자 강화학습(QRL)', 'QUANTUM_TECH'),
    ('양자 광학 (quantum optics)', 'QUANTUM_TECH'),
    ('양자 내성 암호', 'SECURITY_CRYPTO'),
    ('양자 정보 이론 (quantum information theory)', 'QUANTUM_TECH'),
    ('양자 컴퓨팅 알고리즘 (quantum algorithm)', 'QUANTUM_TECH'),
    ('양자 토모그래피 (quantum tomography)', 'QUANTUM_TECH'),
    ('양자 AI (quantum AI)', 'QUANTUM_TECH'),
    ('양자광학 (quantum optics)', 'QUANTUM_TECH'),
    ('양자오류 완화 및 억제 기법 (quantum error mitigation and suppression)', 'QUANTUM_TECH'),
    ('양자전송', 'QUANTUM_TECH'),
    ('양자키분배 (quantum key Distribution, QKD)', 'QUANTUM_TECH'),
    ('에너지 시스템을 위한 QC 및 QML', 'ENERGY_ENVIRONMENT'),
    ('에너지 인포메틱스', 'ENERGY_ENVIRONMENT'),
    ('에너지 ICT', 'ENERGY_ENVIRONMENT'),
    ('에이전트 기반 분산 컴퓨팅', 'SOFTWARE_COMPUTING'),
    ('에이전트 상황 추론', 'AI_ML'),
    ('에이전틱 AI', 'AI_ML'),
    ('연합작전', 'DEFENSE_MILITARY'),
    ('연합학습', 'AI_ML'),
    ('영상 검색', 'SIGNAL_MEDIA'),
    ('영상 압축 및 전송', 'SIGNAL_MEDIA'),
    ('영상 처리', 'SIGNAL_MEDIA'),
    ('영상처리', 'SIGNAL_MEDIA'),
    ('영상처리 프로세서 설계', 'SEMICONDUCTOR_HW'),
    ('오디오 신호 처리', 'SIGNAL_MEDIA'),
    ('워터마킹', 'SIGNAL_MEDIA'),
    ('원자층 공정 (원자층 증착, 원자층 식각)', 'SEMICONDUCTOR_HW'),
    ('웨어러블 센서 에너지 저장 및 변환 소자: 슈퍼커패시터', 'ENERGY_ENVIRONMENT'),
    ('웨어러블 전자소자', 'ELECTRONIC_DEVICES'),
    ('위성통신', 'COMM_NETWORK'),
    ('유기 태양전지(Organic Solar Cell)', 'ENERGY_ENVIRONMENT'),
    ('유무선 통신', 'COMM_NETWORK'),
    ('유연 바이오전자소자', 'BIOMED_HEALTH'),
    ('유연 웨어러블 센서', 'ELECTRONIC_DEVICES'),
    ('유연/박막 센서 플랫폼', 'ELECTRONIC_DEVICES'),
    ('융합 및 처리', 'SIGNAL_MEDIA'),
    ('음성인식', 'SIGNAL_MEDIA'),
    ('음향신호처리', 'SIGNAL_MEDIA'),
    ('음향학', 'SIGNAL_MEDIA'),
    ('응용 인공지능', 'AI_ML'),
    ('의공학', 'BIOMED_HEALTH'),
    ('의료 2D/3D 영상 분석', 'BIOMED_HEALTH'),
    ('의료 영상 기반 딥러닝', 'BIOMED_HEALTH'),
    ('의료 인공지능', 'BIOMED_HEALTH'),
    ('의료영상 분석', 'BIOMED_HEALTH'),
    ('의료영상 분할', 'BIOMED_HEALTH'),
    ('의료영상 합성', 'BIOMED_HEALTH'),
    ('의료영상처리', 'BIOMED_HEALTH'),
    ('의료용 로봇', 'BIOMED_HEALTH'),
    ('의료AI', 'BIOMED_HEALTH'),
    ('이동성 및 위치 측정 기술', 'COMM_NETWORK'),
    ('이동통신', 'COMM_NETWORK'),
    ('이미지 센서 반도체 소자', 'SEMICONDUCTOR_HW'),
    ('이미지 처리', 'SIGNAL_MEDIA'),
    ('이미지/비디오 코딩', 'SIGNAL_MEDIA'),
    ('이미징 AI', 'SIGNAL_MEDIA'),
    ('이상탐지', 'AI_ML'),
    ('인간-로봇 상호작용', 'ROBOT_AUTONOMOUS'),
    ('인간-컴퓨터 상호작용(HCI)', 'HCI_XR'),
    ('인간과 컴퓨터 상호작용', 'HCI_XR'),
    ('인간컴퓨터상호작용', 'HCI_XR'),
    ('인공신경망기반 첨단운전자보조시스템', 'ROBOT_AUTONOMOUS'),
    ('인공지능', 'AI_ML'),
    ('인공지능 기반 설계 기술', 'SEMICONDUCTOR_HW'),
    ('인공지능 기반 영상보안', 'SECURITY_CRYPTO'),
    ('인공지능 보안', 'SECURITY_CRYPTO'),
    ('인공지능 시스템', 'AI_ML'),
    ('인공지능 신경망프로세서 설계', 'SEMICONDUCTOR_HW'),
    ('인공지능 응용', 'AI_ML'),
    ('인공지능 프로젝트 수행', 'POLICY_MANAGEMENT'),
    ('인공지능 하드웨어', 'SEMICONDUCTOR_HW'),
    ('인공지능기반 모빌리티 시스템', 'INDUSTRIAL_MOBILITY'),
    ('인류를 위한 로봇 기술 개발', 'ROBOT_AUTONOMOUS'),
    ('인터랙티브 미디어아트', 'HCI_XR'),
    ('임베디드 시스템', 'SOFTWARE_COMPUTING'),
    ('자기지도학습', 'AI_ML'),
    ('자동제어', 'CONTROL_SYSTEMS'),
    ('자동차 제어/군집주행', 'ROBOT_AUTONOMOUS'),
    ('자세 추정', 'ROBOT_AUTONOMOUS'),
    ('자율운항선박', 'ROBOT_AUTONOMOUS'),
    ('자율주행 모빌리티 제어', 'ROBOT_AUTONOMOUS'),
    ('자율주행 차량 거동계획', 'ROBOT_AUTONOMOUS'),
    ('자율주행을 위한 라이다와 카메라 기반 환경 인지', 'ROBOT_AUTONOMOUS'),
    ('자율주행자동차 환경 인식', 'ROBOT_AUTONOMOUS'),
    ('작업 상황 이해 및 추론', 'ROBOT_AUTONOMOUS'),
    ('잠수함 및 수중운동체 자율화', 'ROBOT_AUTONOMOUS'),
    ('저전력 시스템 구조 설계', 'SEMICONDUCTOR_HW'),
    ('저전력 회로설계', 'SEMICONDUCTOR_HW'),
    ('저차원 금속산화물 나노소재(0D/1D/2D)', 'ELECTRONIC_DEVICES'),
    ('전략도서방위작전', 'DEFENSE_MILITARY'),
    ('전자기적합성', 'SEMICONDUCTOR_HW'),
    ('전자전', 'DEFENSE_MILITARY'),
    ('전쟁사', 'DEFENSE_MILITARY'),
    ('정밀영양', 'BIOMED_HEALTH'),
    ('정보검색', 'DATA_INFORMATION'),
    ('정보보안', 'SECURITY_CRYPTO'),
    ('정보보호 및 사이버보안', 'SECURITY_CRYPTO'),
    ('정보시스템', 'DATA_INFORMATION'),
    ('정보이론', 'COMM_NETWORK'),
    ('정보학', 'DATA_INFORMATION'),
    ('정보화시대의 군사력강화 방안(석사학위 논문, 2001)', 'DEFENSE_MILITARY'),
    ('제어', 'CONTROL_SYSTEMS'),
    ('제어 이론 및 응용', 'CONTROL_SYSTEMS'),
    ('제어공학', 'CONTROL_SYSTEMS'),
    ('증강현실', 'HCI_XR'),
    ('지능 사물', 'COMM_NETWORK'),
    ('지능시스템', 'AI_ML'),
    ('지능형 로봇', 'ROBOT_AUTONOMOUS'),
    ('지능형 모빌리티 시스템 및 제어', 'ROBOT_AUTONOMOUS'),
    ('지능형 모빌리티 제어', 'ROBOT_AUTONOMOUS'),
    ('지능형 바이오시스템 및 뉴럴 엔지니어링', 'BIOMED_HEALTH'),
    ('지능형 반도체 소자/공정', 'SEMICONDUCTOR_HW'),
    ('지능형 보안 시스템 연구', 'SECURITY_CRYPTO'),
    ('지능형 사물인터넷 시스템', 'COMM_NETWORK'),
    ('지능형 시스템', 'AI_ML'),
    ('지능형 시스템을 위한 추정 및 예측', 'CONTROL_SYSTEMS'),
    ('지능형 신호처리', 'SIGNAL_MEDIA'),
    ('지능형 에이전트', 'AI_ML'),
    ('지능형 의사결정', 'AI_ML'),
    ('지능형 이동체 인공지능', 'ROBOT_AUTONOMOUS'),
    ('지능형 제어 및 자동화를 위한 뇌-컴퓨터 인터페이스', 'BIOMED_HEALTH'),
    ('지능형 탐색', 'ROBOT_AUTONOMOUS'),
    ('지능형 통신 네트워크', 'COMM_NETWORK'),
    ('지리공간 인공지능(Geo-AI)', 'DATA_INFORMATION'),
    ('지상', 'ROBOT_AUTONOMOUS'),
    ('진화알고리즘', 'AI_ML'),
    ('집적 광학 (photonic integrated circuit)', 'PHOTONICS_OPTICS'),
    ('집적회로 물리적 설계', 'SEMICONDUCTOR_HW'),
    ('차세대 딥러닝', 'AI_ML'),
    ('차세대 메모리 소자', 'SEMICONDUCTOR_HW'),
    ('차세대 안테나 전자파 잔향실 메타 물질 지능형 산란체 전자장 이론', 'COMM_NETWORK'),
    ('차세대 이동통신(5G/6G) 보안 및 국내외 표준화', 'SECURITY_CRYPTO'),
    ('차세대 통신', 'COMM_NETWORK'),
    ('창업', 'POLICY_MANAGEMENT'),
    ('창의적공학설계', 'POLICY_MANAGEMENT'),
    ('초고속 고출력 광검출기', 'PHOTONICS_OPTICS'),
    ('초고속 보안 시스템', 'SECURITY_CRYPTO'),
    ('최적화', 'CONTROL_SYSTEMS'),
    ('추정', 'CONTROL_SYSTEMS'),
    ('추천시스템', 'AI_ML'),
    ('카메라·레이더·라이다 센서 융합', 'ROBOT_AUTONOMOUS'),
    ('커뮤니케이션 이론', 'COMM_NETWORK'),
    ('컴퓨터 구조', 'SEMICONDUCTOR_HW'),
    ('컴퓨터 그래픽스', 'HCI_XR'),
    ('컴퓨터 네트워크', 'COMM_NETWORK'),
    ('컴퓨터 보조 진단', 'BIOMED_HEALTH'),
    ('컴퓨터 비전', 'SIGNAL_MEDIA'),
    ('컴퓨터 비전 및 제어 시스템', 'ROBOT_AUTONOMOUS'),
    ('컴퓨터 비젼', 'SIGNAL_MEDIA'),
    ('컴퓨터 알고리즘', 'SOFTWARE_COMPUTING'),
    ('컴퓨터 이론', 'SOFTWARE_COMPUTING'),
    ('컴퓨터구조', 'SEMICONDUCTOR_HW'),
    ('컴퓨터그래픽스', 'HCI_XR'),
    ('컴퓨터비전', 'SIGNAL_MEDIA'),
    ('컴퓨터비젼', 'SIGNAL_MEDIA'),
    ('클라우드', 'SOFTWARE_COMPUTING'),
    ('클라우드 서비스 보안', 'SECURITY_CRYPTO'),
    ('클라우드 컴퓨팅', 'SOFTWARE_COMPUTING'),
    ('통계학적신호처리', 'SIGNAL_MEDIA'),
    ('통신 네트워크', 'COMM_NETWORK'),
    ('통신 및 센싱 융합', 'COMM_NETWORK'),
    ('통신 및 영상처리 알고리듬', 'SIGNAL_MEDIA'),
    ('통신 시스템', 'COMM_NETWORK'),
    ('통신 표준', 'COMM_NETWORK'),
    ('통신 프로토콜', 'COMM_NETWORK'),
    ('통신-센싱 융합기술', 'COMM_NETWORK'),
    ('통신신호처리', 'SIGNAL_MEDIA'),
    ('통신용 모뎀 SoC 설계', 'SEMICONDUCTOR_HW'),
    ('통신이론', 'COMM_NETWORK'),
    ('트래픽 엔지니어링', 'COMM_NETWORK'),
    ('패키지 설계 자동화', 'SEMICONDUCTOR_HW'),
    ('패턴 분석', 'DATA_INFORMATION'),
    ('표면·계면 기능화(촉매·금속나노입자·이종접합)', 'ELECTRONIC_DEVICES'),
    ('프라이버시-보존 머신러닝', 'SECURITY_CRYPTO'),
    ('프로젝트 관리', 'POLICY_MANAGEMENT'),
    ('프로토콜 엔지니어링', 'COMM_NETWORK'),
    ('핀테크', 'POLICY_MANAGEMENT'),
    ('하드웨어보안', 'SECURITY_CRYPTO'),
    ('함수 암호', 'SECURITY_CRYPTO'),
    ('항공 MRO', 'INDUSTRIAL_MOBILITY'),
    ('항만 터미널 디지털화', 'INDUSTRIAL_MOBILITY'),
    ('항습·장기신뢰성·저전력 구동', 'ELECTRONIC_DEVICES'),
    ('해상풍력 자율화 및 무인화', 'ENERGY_ENVIRONMENT'),
    ('협력통신 및 전이중 통신', 'COMM_NETWORK'),
    ('화학 가스 센서', 'ELECTRONIC_DEVICES'),
    ('화학저항형 가스센서', 'ELECTRONIC_DEVICES'),
    ('확률 기반 추정론', 'CONTROL_SYSTEMS'),
    ('확장현실', 'HCI_XR'),
    ('확장현실(XR: VR/AR/MR)', 'HCI_XR'),
    ('휴머노이드 로봇', 'ROBOT_AUTONOMOUS'),
    ('힘·압력(Force/Pressure) 센서', 'ELECTRONIC_DEVICES'),
    ('Affective Computing', 'HCI_XR'),
    ('Agentic AI', 'AI_ML'),
    ('Agentic AI 기반 사이버 공방', 'SECURITY_CRYPTO'),
    ('AI', 'AI_ML'),
    ('AI & Visual Computing', 'SIGNAL_MEDIA'),
    ('AI 기반 무인비행체', 'ROBOT_AUTONOMOUS'),
    ('AI 기반 의료 서비스 및 애플리케이션', 'BIOMED_HEALTH'),
    ('AI 기반 자연어 처리(NLP)', 'AI_ML'),
    ('AI 기반 차세대 통신 DNA 저장 장치 시멘틱 통신 양자 정보', 'COMM_NETWORK'),
    ('AI 기반 청정에너지', 'ENERGY_ENVIRONMENT'),
    ('AI 기반 APT 공격 탐지', 'SECURITY_CRYPTO'),
    ('AI 기본 모델링 및 추정', 'CONTROL_SYSTEMS'),
    ('AI 사이버 보안', 'SECURITY_CRYPTO'),
    ('AI Accelerator', 'SEMICONDUCTOR_HW'),
    ('AI-RAN', 'COMM_NETWORK'),
    ('AI/응용특화 가속기 설계', 'SEMICONDUCTOR_HW'),
    ('AI/ML/FL', 'AI_ML'),
    ('AI/ML기반의 악성코드 분석 및 탐지', 'SECURITY_CRYPTO'),
    ('AI로봇', 'ROBOT_AUTONOMOUS'),
    ('AI헬스케어', 'BIOMED_HEALTH'),
    ('AI활용 융합교육', 'POLICY_MANAGEMENT'),
    ('and AIoT', 'COMM_NETWORK'),
    ('Artificial Intelligence (AI,) 최적화 (Optimization)', 'CONTROL_SYSTEMS'),
    ('ASIC 칩 설계', 'SEMICONDUCTOR_HW'),
    ('Biosensor platform for neurotransmitter detection', 'BIOMED_HEALTH'),
    ('CNN기반 비디오코딩', 'SIGNAL_MEDIA'),
    ('Computer Vision', 'SIGNAL_MEDIA'),
    ('Data mining', 'DATA_INFORMATION'),
    ('Deep Learning', 'AI_ML'),
    ('Deep Learning Biometrics (Face Detection & Recognition)', 'SIGNAL_MEDIA'),
    ('Digital Hologram', 'PHOTONICS_OPTICS'),
    ('Digital Holography', 'PHOTONICS_OPTICS'),
    ('Domuent AI', 'AI_ML'),
    ('Edge AI', 'AI_ML'),
    ('Emotional AI', 'HCI_XR'),
    ('Federated Learning', 'AI_ML'),
    ('fractional calculus 응용', 'CONTROL_SYSTEMS'),
    ('GIS', 'DATA_INFORMATION'),
    ('GPU 구조', 'SEMICONDUCTOR_HW'),
    ('HCI', 'HCI_XR'),
    ('Hologram Contents', 'PHOTONICS_OPTICS'),
    ('Holographic Camera', 'PHOTONICS_OPTICS'),
    ('Holographic Coherence Tomography', 'PHOTONICS_OPTICS'),
    ('Holographic Image Recognition', 'SIGNAL_MEDIA'),
    ('Human-Centered AI for Media and Creativity', 'HCI_XR'),
    ('Image Processing', 'SIGNAL_MEDIA'),
    ('Industrial AI Application', 'INDUSTRIAL_MOBILITY'),
    ('intelligent systems', 'AI_ML'),
    ('IoT 보안', 'SECURITY_CRYPTO'),
    ('IT 서비스', 'POLICY_MANAGEMENT'),
    ('IT 정책 경영', 'POLICY_MANAGEMENT'),
    ('IT융합', 'COMM_NETWORK'),
    ('IT융합 디지털신호처리용 프로세서 설계', 'SEMICONDUCTOR_HW'),
    ('LLM', 'AI_ML'),
    ('Machine Learning', 'AI_ML'),
    ('Metaverse System', 'HCI_XR'),
    ('mobile cloudification', 'COMM_NETWORK'),
    ('MPEG', 'SIGNAL_MEDIA'),
    ('MRI 재구성', 'BIOMED_HEALTH'),
    ('Multiple View Geometry', 'SIGNAL_MEDIA'),
    ('network softwarization', 'COMM_NETWORK'),
    ('Neuromorphic devices', 'SEMICONDUCTOR_HW'),
    ('On-device AI', 'AI_ML'),
    ('Pattern Recognition Artificial Intelligence', 'SIGNAL_MEDIA'),
    ('Power semiconductor materials & devices', 'SEMICONDUCTOR_HW'),
    ('Predictive Analytics', 'DATA_INFORMATION'),
    ('Quantum Transfer Computing', 'QUANTUM_TECH'),
    ('RF 집적회로(RFIC)', 'SEMICONDUCTOR_HW'),
    ('RF/마이크로파 집적 센서', 'ELECTRONIC_DEVICES'),
    ('Signal Processor(Audio, Video, Sensor)', 'SEMICONDUCTOR_HW'),
    ('Sim2Real', 'AI_ML'),
    ('SoC 구조 설계', 'SEMICONDUCTOR_HW'),
    ('SoC Design', 'SEMICONDUCTOR_HW'),
    ('Social media', 'DATA_INFORMATION'),
    ('SW 공학', 'SOFTWARE_COMPUTING'),
    ('SW 마케팅', 'POLICY_MANAGEMENT'),
    ('SW 사업 발주 지원 체계', 'POLICY_MANAGEMENT'),
    ('SW 요구 사항 분석', 'SOFTWARE_COMPUTING'),
    ('SW법.제도', 'POLICY_MANAGEMENT'),
    ('Temporal Network Graph Database Graph Mining Internet of Things', 'DATA_INFORMATION'),
    ('Time-series LLM', 'AI_ML'),
    ('UAV 통신', 'COMM_NETWORK'),
    ('UAV/UAM 전주기 설계·개발', 'INDUSTRIAL_MOBILITY'),
    ('UV 광센서/포토디텍터', 'PHOTONICS_OPTICS'),
    ('Video Coding (HEVC, VVC, post VVC)', 'SIGNAL_MEDIA'),
    ('VLSI 설계', 'SEMICONDUCTOR_HW'),
    ('VOC/유해가스 검지', 'ELECTRONIC_DEVICES'),
    ('VR/AR', 'HCI_XR'),
    ('Wearable healthcare sensor platform', 'BIOMED_HEALTH'),
    ('XAI 기반 비전 대규모 언어 모델(VLLM)', 'AI_ML'),
    ('XAI 등', 'AI_ML');

INSERT INTO research_field_category_mapping (research_field_id, category_id)
SELECT field.id, category.id
FROM tmp_research_field_category_seed seed
JOIN research_field field
    ON field.name = seed.research_field_name
JOIN research_field_category category
    ON category.code = seed.category_code
LEFT JOIN research_field_category_mapping existing
    ON existing.research_field_id = field.id
   AND existing.category_id = category.id
WHERE existing.research_field_id IS NULL;

DROP TABLE tmp_research_field_category_seed;
