-- The classification table is a mapping reference only.
-- Do not create research fields that have not gone through the normal registration flow.
CREATE TEMPORARY TABLE tmp_natural_science_category_seed (
    research_field_name VARCHAR(100) NOT NULL,
    category_code VARCHAR(50) NOT NULL,
    CONSTRAINT pk_tmp_natural_science_category_seed
        PRIMARY KEY (research_field_name, category_code)
);

INSERT INTO tmp_natural_science_category_seed (research_field_name, category_code)
VALUES
    ('(2차원 그래핀, MoS2, organic )', 'ELECTRONIC_DEVICES'),
    ('2차원 물질 및 자성체', 'ELECTRONIC_DEVICES'),
    ('가스 동역학', 'PHYSICS_ASTRONOMY'),
    ('격자게이지이론', 'PHYSICS_ASTRONOMY'),
    ('고에너지 입자물리 및 핵물리', 'PHYSICS_ASTRONOMY'),
    ('고에너지 핵물리학', 'PHYSICS_ASTRONOMY'),
    ('고체 물리 실험', 'PHYSICS_ASTRONOMY'),
    ('공생별', 'PHYSICS_ASTRONOMY'),
    ('광전소자', 'PHOTONICS_OPTICS'),
    ('광학', 'PHOTONICS_OPTICS'),
    ('광학 분광법', 'PHOTONICS_OPTICS'),
    ('구상성단 다중종족', 'PHYSICS_ASTRONOMY'),
    ('그래핀', 'ELECTRONIC_DEVICES'),
    ('나노물리학 이론', 'PHYSICS_ASTRONOMY'),
    ('나노전자 소자', 'ELECTRONIC_DEVICES'),
    ('나노전자소재연구실-고체물리실험 (그래핀, 탄소나노튜브, VO2 등의 나노소재 합성 및 응용)', 'ELECTRONIC_DEVICES'),
    ('마이크로&나노 소자', 'ELECTRONIC_DEVICES'),
    ('반도체 재료', 'SEMICONDUCTOR_HW'),
    ('반도체 표면', 'SEMICONDUCTOR_HW'),
    ('성간물질', 'PHYSICS_ASTRONOMY'),
    ('센서', 'ELECTRONIC_DEVICES'),
    ('수냐예프-젤도비치 효과', 'PHYSICS_ASTRONOMY'),
    ('스핀트로닉스 및 스핀칼로리트로닉스', 'ELECTRONIC_DEVICES'),
    ('시감 특성', 'HCI_XR'),
    ('실험입자물리', 'PHYSICS_ASTRONOMY'),
    ('암흑 물질', 'PHYSICS_ASTRONOMY'),
    ('양자 소자', 'QUANTUM_TECH'),
    ('양자 정보 기술 실험', 'QUANTUM_TECH'),
    ('양자광원', 'QUANTUM_TECH'),
    ('양자물질', 'QUANTUM_TECH'),
    ('양자오류정정', 'QUANTUM_TECH'),
    ('양자정보이론-양자센싱', 'QUANTUM_TECH'),
    ('양자학습이론', 'QUANTUM_TECH'),
    ('외부은하', 'PHYSICS_ASTRONOMY'),
    ('우주 거대 구조', 'PHYSICS_ASTRONOMY'),
    ('우주 거대구조', 'PHYSICS_ASTRONOMY'),
    ('우주론', 'PHYSICS_ASTRONOMY'),
    ('우주론적 QUOKKAS 퀘이사 관측', 'PHYSICS_ASTRONOMY'),
    ('은하구조 및 역학', 'PHYSICS_ASTRONOMY'),
    ('은하의 형성 및 진화', 'PHYSICS_ASTRONOMY'),
    ('은하의 형성과 진화', 'PHYSICS_ASTRONOMY'),
    ('응집물질 물리학', 'PHYSICS_ASTRONOMY'),
    ('응집물질물리 이론(나노 자성체, 초전도체)', 'PHYSICS_ASTRONOMY'),
    ('응집물질물리학 이론', 'PHYSICS_ASTRONOMY'),
    ('이론 생물물리학 연체계물리학 통계물리', 'PHYSICS_ASTRONOMY'),
    ('입자물리', 'PHYSICS_ASTRONOMY'),
    ('입자물리 이론/강한상호작용/격자게이지 이론', 'PHYSICS_ASTRONOMY'),
    ('저차원계 응집물질물리(그래핀, 위상절연체)', 'PHYSICS_ASTRONOMY'),
    ('저차원계에서의 전자수송 현상', 'PHYSICS_ASTRONOMY'),
    ('전파 천문학', 'PHYSICS_ASTRONOMY'),
    ('전파천문학', 'PHYSICS_ASTRONOMY'),
    ('중력렌즈', 'PHYSICS_ASTRONOMY'),
    ('중력파', 'PHYSICS_ASTRONOMY'),
    ('중성미자', 'PHYSICS_ASTRONOMY'),
    ('진화 게임 이론 통계 물리학 복잡계 준결정과 타일링', 'PHYSICS_ASTRONOMY'),
    ('천체분광학과 복사 전달 활동성 은하', 'PHYSICS_ASTRONOMY'),
    ('초장기선 전파간섭계(VLBI)', 'PHYSICS_ASTRONOMY'),
    ('초전도 양자 시스템', 'QUANTUM_TECH'),
    ('초전도 양자 컴퓨팅', 'QUANTUM_TECH'),
    ('측광 필터 개발 (JWL 측광계)', 'PHYSICS_ASTRONOMY'),
    ('포토디텍터', 'PHOTONICS_OPTICS'),
    ('항성 분광 및 측광학', 'PHYSICS_ASTRONOMY'),
    ('항성종족론', 'PHYSICS_ASTRONOMY'),
    ('핵물리', 'PHYSICS_ASTRONOMY'),
    ('행성상성운의 방출선과 산란선 형성 우주 재이온화 라이먼 방출 은하', 'PHYSICS_ASTRONOMY'),
    ('허블도 기반 거리-적색편이 관계 측정', 'PHYSICS_ASTRONOMY'),
    ('활동은하핵 및 초대질량 블랙홀 관측', 'PHYSICS_ASTRONOMY'),
    ('AR/VR/3D 디스플레이', 'HCI_XR'),
    ('hBN', 'ELECTRONIC_DEVICES'),
    ('KVN·Mopra 기반 초장기선 전파간섭계 관측', 'PHYSICS_ASTRONOMY'),
    ('p-n 접합', 'SEMICONDUCTOR_HW'),
    ('TMD 등 2차원 물질 및 탄소나노튜브', 'ELECTRONIC_DEVICES'),
    ('van der Waals 이종구조접합', 'ELECTRONIC_DEVICES'),
    ('가사이드 이론', 'MATH_STATISTICS'),
    ('기하군론', 'MATH_STATISTICS'),
    ('기하위상', 'MATH_STATISTICS'),
    ('다중척도방법', 'MATH_STATISTICS'),
    ('대수적 정수론', 'MATH_STATISTICS'),
    ('땋임군', 'MATH_STATISTICS'),
    ('리군론', 'MATH_STATISTICS'),
    ('리대수', 'MATH_STATISTICS'),
    ('리만기하', 'MATH_STATISTICS'),
    ('머신러닝 이론', 'AI_ML'),
    ('비모수회귀분석', 'MATH_STATISTICS'),
    ('생물통계학', 'BIOMED_HEALTH'),
    ('생존분석', 'BIOMED_HEALTH'),
    ('선형대수학 및 머신러닝', 'AI_ML'),
    ('수치해석', 'MATH_STATISTICS'),
    ('수학교육론', 'POLICY_MANAGEMENT'),
    ('암호론', 'SECURITY_CRYPTO'),
    ('양자정보 및 양자암호', 'QUANTUM_TECH'),
    ('유전체 연구', 'BIOMED_HEALTH'),
    ('이미지 처리', 'SIGNAL_MEDIA'),
    ('이와사와 이론', 'MATH_STATISTICS'),
    ('인공지능수학', 'AI_ML'),
    ('작용소론', 'MATH_STATISTICS'),
    ('조합론', 'MATH_STATISTICS'),
    ('퍼지수학', 'MATH_STATISTICS'),
    ('표현론', 'MATH_STATISTICS'),
    ('함수해석학', 'MATH_STATISTICS'),
    ('해석학', 'MATH_STATISTICS'),
    ('1', 'CHEMISTRY_MATERIALS'),
    ('4D 프린팅용 소재', 'CHEMISTRY_MATERIALS'),
    ('강유전 소재', 'ELECTRONIC_DEVICES'),
    ('계산/전산 화학', 'CHEMISTRY_MATERIALS'),
    ('고분자 가공', 'CHEMISTRY_MATERIALS'),
    ('고분자 구조-물성', 'CHEMISTRY_MATERIALS'),
    ('고분자 기반 기체 분리막의 개발 및 성능 평가 연구', 'CHEMISTRY_MATERIALS'),
    ('고분자 소재 합성', 'CHEMISTRY_MATERIALS'),
    ('고분자 열역학', 'CHEMISTRY_MATERIALS'),
    ('고분자 재활용 및 분석', 'ENERGY_ENVIRONMENT'),
    ('고분자 화학 (고분자 합성) 4', 'CHEMISTRY_MATERIALS'),
    ('고분자복합재료', 'CHEMISTRY_MATERIALS'),
    ('광결정 디바이스(화학 센서·반사형 디스플레이·레이저)', 'PHOTONICS_OPTICS'),
    ('금속산화물 나노입자(titania·zirconia·silica)', 'CHEMISTRY_MATERIALS'),
    ('기능성 고분자', 'CHEMISTRY_MATERIALS'),
    ('기능성 고분자 복합소재', 'CHEMISTRY_MATERIALS'),
    ('나노 반도체 소재', 'SEMICONDUCTOR_HW'),
    ('나노소재 (금, 은, 백금, 하이브리드 나노입자 및 양자점의 제조 및 특성 분석)', 'CHEMISTRY_MATERIALS'),
    ('다양한 응용 분야를 위한 그래핀-고분자 복합재료 개발 2', 'CHEMISTRY_MATERIALS'),
    ('단백질-단백질 상호작용 연구', 'BIOMED_HEALTH'),
    ('단백질-리간드 상호작용 방법론', 'BIOMED_HEALTH'),
    ('단백질의 구조 및 기능 연구', 'BIOMED_HEALTH'),
    ('대사물질 프로파일링', 'BIOMED_HEALTH'),
    ('레독스 플로우 배터리 및 이차전지용 고분자 전해질의 설계', 'ENERGY_ENVIRONMENT'),
    ('물리화학', 'CHEMISTRY_MATERIALS'),
    ('바이오 센서', 'BIOMED_HEALTH'),
    ('바이오 소재(Organoid·Embolic materials·GelMA)', 'BIOMED_HEALTH'),
    ('바이오메디컬 소재', 'BIOMED_HEALTH'),
    ('분자동력학', 'CHEMISTRY_MATERIALS'),
    ('비트리머', 'CHEMISTRY_MATERIALS'),
    ('빌량분석법', 'CHEMISTRY_MATERIALS'),
    ('상전이 거동', 'CHEMISTRY_MATERIALS'),
    ('생물리화학', 'BIOMED_HEALTH'),
    ('생분해 에너지 소재', 'ENERGY_ENVIRONMENT'),
    ('생유기화학 펩타이드 및 항암제 합성 항체를 이용한 항암제 전달', 'BIOMED_HEALTH'),
    ('생체 흡수성 전자 소재', 'BIOMED_HEALTH'),
    ('소재특성분석', 'CHEMISTRY_MATERIALS'),
    ('실시간 복합분석', 'CHEMISTRY_MATERIALS'),
    ('엑스선 산란', 'CHEMISTRY_MATERIALS'),
    ('연료전지', 'ENERGY_ENVIRONMENT'),
    ('연료전지(DMFC·PEMFC)', 'ENERGY_ENVIRONMENT'),
    ('열분석법', 'CHEMISTRY_MATERIALS'),
    ('열분해', 'CHEMISTRY_MATERIALS'),
    ('원자력 현미경(AFM)을 이용한 접착력 연구 3', 'CHEMISTRY_MATERIALS'),
    ('이차전지', 'ENERGY_ENVIRONMENT'),
    ('자동차용 소재', 'INDUSTRIAL_MOBILITY'),
    ('재조합 단백질 생산', 'BIOMED_HEALTH'),
    ('전극/전해질 계면', 'ENERGY_ENVIRONMENT'),
    ('전기화학', 'CHEMISTRY_MATERIALS'),
    ('전기화학적 분석 및 진단', 'CHEMISTRY_MATERIALS'),
    ('전자정보용 화학소재', 'ELECTRONIC_DEVICES'),
    ('천연 우루시올의 화학 구조–물성 상관관계 연구', 'CHEMISTRY_MATERIALS'),
    ('친환경 고분자', 'ENERGY_ENVIRONMENT'),
    ('콜로이드 합성 및 자기조립', 'CHEMISTRY_MATERIALS'),
    ('크로마토그래피', 'CHEMISTRY_MATERIALS'),
    ('크로마토그래피 분리분석', 'CHEMISTRY_MATERIALS'),
    ('태양전지', 'ENERGY_ENVIRONMENT'),
    ('태양전지(DSSC·OPV)', 'ENERGY_ENVIRONMENT'),
    ('폐수 중금속 이온 흡착 및 약물 전달을 위한 젤라틴 기반 하이드로겔 입자 제조 5', 'BIOMED_HEALTH'),
    ('하이브리드 소재', 'CHEMISTRY_MATERIALS'),
    ('합성 및 특성 연구', 'CHEMISTRY_MATERIALS'),
    ('화학소재 분석', 'CHEMISTRY_MATERIALS'),
    ('환경분석', 'ENERGY_ENVIRONMENT'),
    ('LCD colorant materials', 'ELECTRONIC_DEVICES'),
    ('NMR 분광학', 'CHEMISTRY_MATERIALS');

INSERT INTO research_field_category_mapping (research_field_id, category_id)
SELECT field.id, category.id
FROM tmp_natural_science_category_seed seed
JOIN research_field field
    ON field.name = seed.research_field_name
JOIN research_field_category category
    ON category.code = seed.category_code
LEFT JOIN research_field_category_mapping existing
    ON existing.research_field_id = field.id
   AND existing.category_id = category.id
WHERE existing.research_field_id IS NULL;

DROP TABLE tmp_natural_science_category_seed;
