-- Curated reference for 193 reviewed life-science fields (247 category pairs).
-- Do not create research fields or depend on local numeric IDs.
-- Short source fragments retain their reviewed names; see docs/life-science-research-field-categories.md.
CREATE TEMPORARY TABLE tmp_life_science_category_seed (
    research_field_name VARCHAR(100) NOT NULL,
    category_code VARCHAR(50) NOT NULL,
    CONSTRAINT pk_tmp_life_science_category_seed PRIMARY KEY (research_field_name, category_code)
);

INSERT INTO tmp_life_science_category_seed (research_field_name, category_code)
VALUES
    ('지소화성탄수화물', 'FOOD_NUTRITION'),
    ('혈당스파이크', 'BIOMED_HEALTH'),
    ('혈당스파이크', 'FOOD_NUTRITION'),
    ('다당체', 'CHEMISTRY_MATERIALS'),
    ('다당체', 'MOLECULAR_BIOTECH'),
    ('소화조절', 'FOOD_NUTRITION'),
    ('신규 기능성 탄수화물소재의 효소적 바이오 프로세스', 'FOOD_NUTRITION'),
    ('기능적 특성이 향상된 탄수화물소재의 분자구조 설계 및 특성 분석', 'CHEMISTRY_MATERIALS'),
    ('기능적 특성이 향상된 탄수화물소재의 분자구조 설계 및 특성 분석', 'FOOD_NUTRITION'),
    ('효소활성 제어 소재 발굴 및 제어 기작 규명', 'MOLECULAR_BIOTECH'),
    ('기능성 성분의 생체적합형 체내 전달시스템 개발', 'BIOMED_HEALTH'),
    ('천연물 유래 고감미소재 및 효소적 합성 대체 감미소재 개발', 'FOOD_NUTRITION'),
    ('식품 인공지능', 'AI_ML'),
    ('식품 인공지능', 'FOOD_NUTRITION'),
    ('식품 가공 및 공학', 'FOOD_NUTRITION'),
    ('식품 물성', 'FOOD_NUTRITION'),
    ('phytochemicals의 생체이용률 평가 phytochemicals을 이용한 디톡스 효능 평가 빅테이터 AI를 활용한 식품안전관리', 'AI_ML'),
    ('phytochemicals의 생체이용률 평가 phytochemicals을 이용한 디톡스 효능 평가 빅테이터 AI를 활용한 식품안전관리', 'FOOD_NUTRITION'),
    ('기능성식품개발', 'FOOD_NUTRITION'),
    ('대체식품(배양육, 식물고기) 개발', 'FOOD_NUTRITION'),
    ('최신정밀영양생리기반 식품 및 사료 개발', 'FOOD_NUTRITION'),
    ('식품 신가공 기술 개발 가열 및 비가열 살균 기술 개발 식품의 냉동 및 과냉각 저장 기술 개발 식물성 대체 식육 제품 개발', 'FOOD_NUTRITION'),
    ('장내 마이크로바이옴', 'BIOMED_HEALTH'),
    ('장내 마이크로바이옴', 'FOOD_NUTRITION'),
    ('장내 마이크로바이옴', 'MOLECULAR_BIOTECH'),
    ('프리바이오틱스', 'FOOD_NUTRITION'),
    ('프로바이오틱스', 'FOOD_NUTRITION'),
    ('신바이오틱스', 'FOOD_NUTRITION'),
    ('포스트바이오틱스', 'FOOD_NUTRITION'),
    ('메타볼로믹스', 'MOLECULAR_BIOTECH'),
    ('박테리오페이지', 'MOLECULAR_BIOTECH'),
    ('천연자원유래 건강기능식품소재 개발 및 작용기전 규명', 'FOOD_NUTRITION'),
    ('합성생물학 기반 세포공장 구축을 통한 기능성 소재 생산(식품, 화장품)', 'FOOD_NUTRITION'),
    ('합성생물학 기반 세포공장 구축을 통한 기능성 소재 생산(식품, 화장품)', 'MOLECULAR_BIOTECH'),
    ('세포공장 구축 자동화 플랫폼 개발', 'MOLECULAR_BIOTECH'),
    ('차세대 효소 기능 탐색 및 대사경로 최적화', 'MOLECULAR_BIOTECH'),
    ('미생물 생명공학', 'MOLECULAR_BIOTECH'),
    ('유전자 복제', 'MOLECULAR_BIOTECH'),
    ('효소학', 'MOLECULAR_BIOTECH'),
    ('식물-미생물 상호작용', 'PLANT_AGRICULTURE'),
    ('식물 병리학', 'PLANT_AGRICULTURE'),
    ('미생물 매개 스트레스 완화', 'MOLECULAR_BIOTECH'),
    ('미생물 매개 스트레스 완화', 'PLANT_AGRICULTURE'),
    ('나노기술', 'CHEMISTRY_MATERIALS'),
    ('메타분석', 'MATH_STATISTICS'),
    ('Food Science and Microbiology', 'FOOD_NUTRITION'),
    ('Animal Nutrition and Meat Science', 'FOOD_NUTRITION'),
    ('Nutrition and Gut Health Interactions', 'BIOMED_HEALTH'),
    ('Nutrition and Gut Health Interactions', 'FOOD_NUTRITION'),
    ('Bio-active Compounds of Natural Products', 'CHEMISTRY_MATERIALS'),
    ('Bio-active Compounds of Natural Products', 'MOLECULAR_BIOTECH'),
    ('Biomaterial Synthesis and Biomedical Applications', 'BIOMED_HEALTH'),
    ('Biomaterial Synthesis and Biomedical Applications', 'CHEMISTRY_MATERIALS'),
    ('Human Health', 'BIOMED_HEALTH'),
    ('Neurodegenerative and neuropsychiatric diseases', 'BIOMED_HEALTH'),
    ('Genes', 'MOLECULAR_BIOTECH'),
    ('brain', 'BIOMED_HEALTH'),
    ('environment and behavior', 'BIOMED_HEALTH'),
    ('The Microbiota-Gut-brain axis in behavior and brain disorders', 'BIOMED_HEALTH'),
    ('히스톤변형과 연관된 후성유전체 연구', 'MOLECULAR_BIOTECH'),
    ('줄기세포의 유지 및 분화기전 연구', 'MOLECULAR_BIOTECH'),
    ('유전자 적중 마우스 모델을 이용한 다양한 후성유전학 연구', 'MOLECULAR_BIOTECH'),
    ('항암 및 주름개선용 레티노이드계 물질 개발', 'BIOMED_HEALTH'),
    ('단백질 결집 질환 (파킨슨병, 간경변 등)의 발병 요인 연구 단백질의 구조와 기능의 연관성 단백질 의약품 개발', 'BIOMED_HEALTH'),
    ('벼-벼도열병균 상호작용을 모델로 한 식물 면역학 연구', 'PLANT_AGRICULTURE'),
    ('벼도열병 이펙터 인식에 의한 벼 면역반응 과정의 과민성세포사멸 메커니즘 연구', 'PLANT_AGRICULTURE'),
    ('철-', 'PLANT_AGRICULTURE'),
    ('활성산소-의존성 페롭토시스에 의한 식물면역 메커니즘 연구', 'PLANT_AGRICULTURE'),
    ('간암의 후성유전학적 마커 분석 및 진단법 개발 모델 생물체를 이용한 질병 원인 분석', 'BIOMED_HEALTH'),
    ('자가면역 뇌척수염 및 아토피 피부질환 기전', 'BIOMED_HEALTH'),
    ('자연살해능 면역세포(NK 세포, NKT 세포, NKDC)의 항암면역 기전', 'BIOMED_HEALTH'),
    ('염증성 장질환 및 점막면역 기전', 'BIOMED_HEALTH'),
    ('천연물 및 나노물질의 면역활성 기전', 'BIOMED_HEALTH'),
    ('뇌신경 질환 원인 규명', 'BIOMED_HEALTH'),
    ('뇌신경 질환 치료제 개발', 'BIOMED_HEALTH'),
    ('아연 중심의 신경생물학', 'BIOMED_HEALTH'),
    ('세포사멸 및 분화', 'MOLECULAR_BIOTECH'),
    ('신경발생 및 관련 신경정신질환', 'BIOMED_HEALTH'),
    ('Developmental Regulatory Networks for Photomorphogenesis', 'PLANT_AGRICULTURE'),
    ('Epigenetic Control of Plant Development', 'PLANT_AGRICULTURE'),
    ('Hormonal Signaling', 'MOLECULAR_BIOTECH'),
    ('Hormonal Signaling', 'PLANT_AGRICULTURE'),
    ('Mode of Action of Smoke-derived Small Molecules', 'PLANT_AGRICULTURE'),
    ('단백질 구조 기반 가상 스크리닝 및 신약후보물질 발굴', 'BIOMED_HEALTH'),
    ('인공지능 기반 신약후보물질 약리학적 물성 예측', 'AI_ML'),
    ('인공지능 기반 신약후보물질 약리학적 물성 예측', 'BIOMED_HEALTH'),
    ('분자 모델링 기반 단백질 의약품 설계', 'BIOMED_HEALTH'),
    ('바이오나노 약물전달시스템 연구실', 'BIOMED_HEALTH'),
    ('화합물 약물의 약효 증진 또는 부작용 감소를 위한 전달시스템 연구', 'BIOMED_HEALTH'),
    ('전달시스템을 활용한 바이오베터 개발 연구', 'BIOMED_HEALTH'),
    ('약물전달체로서 지질나노입자의 기능 및 구조 연구', 'BIOMED_HEALTH'),
    ('암줄기세포', 'BIOMED_HEALTH'),
    ('줄기세포생물학', 'BIOMED_HEALTH'),
    ('줄기세포생물학', 'MOLECULAR_BIOTECH'),
    ('항체치료제', 'BIOMED_HEALTH'),
    ('종양 미세 환경과 EMT 연구 --> 항암제 내성 극복', 'BIOMED_HEALTH'),
    ('염증반응과 면역 B 세포 연구 --> 면역 조절제 발굴', 'BIOMED_HEALTH'),
    ('선천면역', 'BIOMED_HEALTH'),
    ('종양면역', 'BIOMED_HEALTH'),
    ('면역조절신호전달네트워크', 'BIOMED_HEALTH'),
    ('면역치료제', 'BIOMED_HEALTH'),
    ('첨단면역공학기술', 'BIOMED_HEALTH'),
    ('RNA 생물학 유전체학 생물정보학', 'DATA_INFORMATION'),
    ('RNA 생물학 유전체학 생물정보학', 'MOLECULAR_BIOTECH'),
    ('합성생물학', 'MOLECULAR_BIOTECH'),
    ('조직공학', 'BIOMED_HEALTH'),
    ('인공세포', 'MOLECULAR_BIOTECH'),
    ('줄기세포', 'BIOMED_HEALTH'),
    ('줄기세포', 'MOLECULAR_BIOTECH'),
    ('심장학', 'BIOMED_HEALTH'),
    ('인간 만능줄기세포', 'BIOMED_HEALTH'),
    ('인간 만능줄기세포', 'MOLECULAR_BIOTECH'),
    ('줄기세포학', 'BIOMED_HEALTH'),
    ('줄기세포학', 'MOLECULAR_BIOTECH'),
    ('질병 모델링', 'BIOMED_HEALTH'),
    ('신경퇴행성 질환', 'BIOMED_HEALTH'),
    ('파킨슨병', 'BIOMED_HEALTH'),
    ('말초신경계 질환', 'BIOMED_HEALTH'),
    ('신약 발굴 스크리닝 플랫폼 개발', 'BIOMED_HEALTH'),
    ('대사생화학', 'MOLECULAR_BIOTECH'),
    ('대사체학', 'MOLECULAR_BIOTECH'),
    ('세포생물학', 'MOLECULAR_BIOTECH'),
    ('생체재료', 'BIOMED_HEALTH'),
    ('생체재료', 'CHEMISTRY_MATERIALS'),
    ('재생의학', 'BIOMED_HEALTH'),
    ('약물전달', 'BIOMED_HEALTH'),
    ('환경호르몬의 건강영향', 'BIOMED_HEALTH'),
    ('환경호르몬의 건강영향', 'ENERGY_ENVIRONMENT'),
    ('유전체에 따른 질환발생 민감성', 'BIOMED_HEALTH'),
    ('유전체에 따른 질환발생 민감성', 'MOLECULAR_BIOTECH'),
    ('생체시료 기반 바이오모니터링', 'BIOMED_HEALTH'),
    ('후성유전체 조절과 질병발생 기전', 'BIOMED_HEALTH'),
    ('항암치료 저항성', 'BIOMED_HEALTH'),
    ('종양발생', 'BIOMED_HEALTH'),
    ('리보솜 생합성', 'MOLECULAR_BIOTECH'),
    ('핵인 단백질', 'MOLECULAR_BIOTECH'),
    ('소뇌 발달', 'BIOMED_HEALTH'),
    ('핵내막 단백질 네트워크의 구조적·기능적 역할 규명 및 세포 신호전달 조절 기전 연구', 'MOLECULAR_BIOTECH'),
    ('핵내막 단백질의 비구조적 기능과 생명현상 유지 메커니즘 연구', 'MOLECULAR_BIOTECH'),
    ('핵내막 단백질 유전자 돌연변이에 의한 근육이상 질환 발병 기전 연구 (제브라피시 모델 활용)', 'BIOMED_HEALTH'),
    ('식물의 중금속 저항성 및 축적 기전 규명', 'ENERGY_ENVIRONMENT'),
    ('식물의 중금속 저항성 및 축적 기전 규명', 'PLANT_AGRICULTURE'),
    ('유전자교정 이용 중금속 정화용 식물 개발', 'ENERGY_ENVIRONMENT'),
    ('유전자교정 이용 중금속 정화용 식물 개발', 'PLANT_AGRICULTURE'),
    ('유전자교정 이용 중금속 저축적 농작물 개발', 'ENERGY_ENVIRONMENT'),
    ('유전자교정 이용 중금속 저축적 농작물 개발', 'PLANT_AGRICULTURE'),
    ('유전자교정 이용 맞춤형 기능성 불포화 지방산 합성 들깨 개발', 'PLANT_AGRICULTURE'),
    ('애기장대의 CBL-CIPK 칼슘신호전달 기작 유전자교정 기술을 활용한 형질개선 토마토 종자 개발 천연고무 생산을 위한 야생상추의 바이오엔지니어링', 'PLANT_AGRICULTURE'),
    ('화훼 유전 및 육종', 'PLANT_AGRICULTURE'),
    ('유용형질 탐색', 'MOLECULAR_BIOTECH'),
    ('유용형질 탐색', 'PLANT_AGRICULTURE'),
    ('기능성물질분석 및 소재개발', 'CHEMISTRY_MATERIALS'),
    ('기능성물질분석 및 소재개발', 'PLANT_AGRICULTURE'),
    ('화훼류 수확후 관리 및 유통시스템', 'PLANT_AGRICULTURE'),
    ('식물 육종학(32년간 무 품종 육성) 식물 유전학', 'PLANT_AGRICULTURE'),
    ('식물 비교 유전체 연구', 'MOLECULAR_BIOTECH'),
    ('식물 비교 유전체 연구', 'PLANT_AGRICULTURE'),
    ('유전체 육종 기술 개발', 'PLANT_AGRICULTURE'),
    ('천연물 소재 생산용 대사공학 기술 개발', 'MOLECULAR_BIOTECH'),
    ('기능성 소재 개발', 'MOLECULAR_BIOTECH'),
    ('기능성 소재 개발', 'PLANT_AGRICULTURE'),
    ('식물분자병리', 'PLANT_AGRICULTURE'),
    ('식물면역', 'PLANT_AGRICULTURE'),
    ('면역 수용체 매개 신호전달', 'MOLECULAR_BIOTECH'),
    ('면역 수용체 매개 신호전달', 'PLANT_AGRICULTURE'),
    ('펩타이드 호르몬', 'MOLECULAR_BIOTECH'),
    ('펩타이드 호르몬', 'PLANT_AGRICULTURE'),
    ('면역유도체', 'MOLECULAR_BIOTECH'),
    ('면역유도체', 'PLANT_AGRICULTURE'),
    ('식물유전육종', 'PLANT_AGRICULTURE'),
    ('전장유전체연관분석', 'MOLECULAR_BIOTECH'),
    ('전장유전체연관분석', 'PLANT_AGRICULTURE'),
    ('유전체 선발', 'PLANT_AGRICULTURE'),
    ('데이터 기반 정밀 육종', 'DATA_INFORMATION'),
    ('데이터 기반 정밀 육종', 'PLANT_AGRICULTURE'),
    ('박과 채소작물 유용 유전자 발굴 및 분자표지 개발 병저항성', 'PLANT_AGRICULTURE'),
    ('환경스트레스 저항성 품종 개발', 'PLANT_AGRICULTURE'),
    ('식물 지질대사', 'MOLECULAR_BIOTECH'),
    ('식물 지질대사', 'PLANT_AGRICULTURE'),
    ('분자생물학', 'MOLECULAR_BIOTECH'),
    ('유전학', 'MOLECULAR_BIOTECH'),
    ('대사공학', 'MOLECULAR_BIOTECH'),
    ('유전자편집', 'MOLECULAR_BIOTECH'),
    ('Aptamer를 이용한 항암면역 치료제 개발', 'BIOMED_HEALTH'),
    ('Aptamer를 이용한 산업 액체 폐기물 처리 기술 개발', 'ENERGY_ENVIRONMENT'),
    ('개발된 압타머를 산업 현장 적용', 'MOLECULAR_BIOTECH'),
    ('중금속 및 환경호르몬에 의한 식물 뿌리발달과 신호전달', 'ENERGY_ENVIRONMENT'),
    ('중금속 및 환경호르몬에 의한 식물 뿌리발달과 신호전달', 'PLANT_AGRICULTURE'),
    ('식물 스트레스 반응과 신호전달', 'PLANT_AGRICULTURE'),
    ('생명공학 기반 고기능성 작물 개발', 'PLANT_AGRICULTURE'),
    ('식물유전체', 'MOLECULAR_BIOTECH'),
    ('식물유전체', 'PLANT_AGRICULTURE'),
    ('후성유전체', 'MOLECULAR_BIOTECH'),
    ('유전자교정', 'MOLECULAR_BIOTECH'),
    ('유전자교정', 'PLANT_AGRICULTURE'),
    ('대사경로', 'MOLECULAR_BIOTECH'),
    ('콩', 'PLANT_AGRICULTURE'),
    ('식용', 'FOOD_NUTRITION'),
    ('약용', 'BIOMED_HEALTH'),
    ('약용', 'PLANT_AGRICULTURE'),
    ('사료용 곤충', 'FOOD_NUTRITION'),
    ('사료용 곤충', 'PLANT_AGRICULTURE'),
    ('초파리 장재생 연구', 'BIOMED_HEALTH'),
    ('초파리 장재생 연구', 'MOLECULAR_BIOTECH'),
    ('선천성 면역', 'BIOMED_HEALTH'),
    ('선천성 면역', 'MOLECULAR_BIOTECH'),
    ('항균펩타이드', 'BIOMED_HEALTH'),
    ('항균펩타이드', 'MOLECULAR_BIOTECH'),
    ('육종', 'PLANT_AGRICULTURE'),
    ('벼', 'PLANT_AGRICULTURE'),
    ('약용작물', 'PLANT_AGRICULTURE'),
    ('유전체육종', 'PLANT_AGRICULTURE'),
    ('기후변화', 'ENERGY_ENVIRONMENT'),
    ('비생물스트레스저항성', 'PLANT_AGRICULTURE'),
    ('농업 로봇 및 AI', 'AI_ML'),
    ('농업 로봇 및 AI', 'PLANT_AGRICULTURE'),
    ('농업 로봇 및 AI', 'ROBOT_AUTONOMOUS'),
    ('스마트농업', 'INDUSTRIAL_MOBILITY'),
    ('스마트농업', 'PLANT_AGRICULTURE'),
    ('농업 자동화', 'INDUSTRIAL_MOBILITY'),
    ('농업 자동화', 'PLANT_AGRICULTURE'),
    ('기능성 식물 및 다양한 자원식물의 유전 다양성 연구와 식물 오믹스 정보 기반 디지털 육종을 이용한 품종 육종', 'DATA_INFORMATION'),
    ('기능성 식물 및 다양한 자원식물의 유전 다양성 연구와 식물 오믹스 정보 기반 디지털 육종을 이용한 품종 육종', 'PLANT_AGRICULTURE'),
    ('천연물 발굴·구조 규명 및 생리활성 연구', 'CHEMISTRY_MATERIALS'),
    ('천연물 발굴·구조 규명 및 생리활성 연구', 'MOLECULAR_BIOTECH'),
    ('분광학', 'CHEMISTRY_MATERIALS'),
    ('질량분석', 'CHEMISTRY_MATERIALS'),
    ('분자 네트워킹', 'CHEMISTRY_MATERIALS'),
    ('유용 이차대사산물 탐색 및 기능 규명', 'CHEMISTRY_MATERIALS'),
    ('유용 이차대사산물 탐색 및 기능 규명', 'MOLECULAR_BIOTECH'),
    ('나노의학 기반 암 면역조절 플랫폼', 'BIOMED_HEALTH'),
    ('세포외소포체(EV)', 'BIOMED_HEALTH'),
    ('세포외소포체(EV)', 'MOLECULAR_BIOTECH'),
    ('고분자–약물 접합체(PDC)', 'BIOMED_HEALTH'),
    ('고분자–약물 접합체(PDC)', 'CHEMISTRY_MATERIALS'),
    ('생체모사 약물전달시스템', 'BIOMED_HEALTH'),
    ('종양 유래 엑소좀의 면역억제 미세환경 조절 및 면역관문억제제 불응성 극복', 'BIOMED_HEALTH'),
    ('반응성·표적성 약물전달체', 'BIOMED_HEALTH'),
    ('어류생리학 및 환경독성학', 'BIOMED_HEALTH'),
    ('어류생리학 및 환경독성학', 'ENERGY_ENVIRONMENT'),
    ('LC-MS 기반 대사체학 및 지질체학', 'CHEMISTRY_MATERIALS'),
    ('LC-MS 기반 대사체학 및 지질체학', 'MOLECULAR_BIOTECH'),
    ('생리활성 천연물의 대사 조절 기전 연구', 'MOLECULAR_BIOTECH'),
    ('안정 동위원소 추적(stable isotope tracing)을 이용한 대사 플럭스 연구', 'MOLECULAR_BIOTECH'),
    ('감염면역', 'BIOMED_HEALTH'),
    ('신약개발', 'BIOMED_HEALTH'),
    ('기능성 제품개발 연구', 'BIOMED_HEALTH');

INSERT INTO research_field_category_mapping (research_field_id, category_id)
SELECT field.id, category.id
FROM tmp_life_science_category_seed seed
JOIN research_field field ON field.name = seed.research_field_name
JOIN research_field_category category ON category.code = seed.category_code
LEFT JOIN research_field_category_mapping existing
    ON existing.research_field_id = field.id AND existing.category_id = category.id
WHERE existing.research_field_id IS NULL;

DROP TABLE tmp_life_science_category_seed;
