-- Issue #76: reviewed public faculty catalogue, captured 2026-09-15.
-- 30 sources / 332 department memberships / 303 distinct professors and labs.
-- Deployment data, NOT a local/test seed. No accounts, tokens or research-field mappings.
-- record_key is an internal staging ordinal, NEVER a local database primary key.
-- Resolve real IDs by email (or NULL-email + college/department/name); preserve existing
-- profiles, official lab names, recruitment state, audit rows and all existing IDs.
-- MySQL DDL is not transactional. Guards stop ambiguous identities; insert-only writes
-- and scoped staging cleanup allow retry after inspection/backup recovery + Flyway repair.

DROP TABLE IF EXISTS v44_catalog_guard;
DROP TABLE IF EXISTS v44_catalog_affiliation;
DROP TABLE IF EXISTS v44_catalog_professor;
DROP TABLE IF EXISTS v44_catalog_source;

CREATE TABLE v44_catalog_source (
    college_name VARCHAR(100) NOT NULL,
    department_name VARCHAR(100) NOT NULL,
    source_name VARCHAR(150) NOT NULL,
    source_url VARCHAR(512) NOT NULL PRIMARY KEY,
    parser_type VARCHAR(50) NOT NULL,
    department_id BIGINT NULL
);
CREATE TABLE v44_catalog_professor (
    record_key INT NOT NULL PRIMARY KEY,
    college_name VARCHAR(100) NOT NULL,
    department_name VARCHAR(100) NOT NULL,
    professor_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NULL,
    position VARCHAR(100) NULL,
    laboratory_name VARCHAR(150) NOT NULL,
    website_url VARCHAR(2048) NULL,
    description VARCHAR(2000) NULL,
    department_id BIGINT NULL,
    professor_id BIGINT NULL,
    laboratory_id BIGINT NULL
);
CREATE TABLE v44_catalog_affiliation (
    record_key INT NOT NULL,
    college_name VARCHAR(100) NOT NULL,
    department_name VARCHAR(100) NOT NULL,
    position VARCHAR(100) NULL,
    department_id BIGINT NULL,
    PRIMARY KEY (record_key, college_name, department_name)
);
CREATE TABLE v44_catalog_guard (
    reason VARCHAR(100) NOT NULL,
    violations INT NOT NULL,
    CONSTRAINT ck_v44_catalog_no_conflicts CHECK (violations = 0)
);

INSERT INTO v44_catalog_source (college_name, department_name, source_name, source_url, parser_type)
VALUES
    ('공과대학', '건축공학과', '건축공학과 교수진', 'https://dept.sejong.ac.kr/archeng/intro/professor.do', 'SEJONG_STANDARD'),
    ('공과대학', '건축학과', '건축학과 교수진', 'https://dept.sejong.ac.kr/architecture/intro/professor.do', 'SEJONG_STANDARD'),
    ('공과대학', '건설환경공학과', '건설환경공학과 교수진', 'https://dept.sejong.ac.kr/builddpt/intro/professor.do', 'SEJONG_STANDARD'),
    ('공과대학', '환경융합공학과', '환경융합공학과 교수진', 'https://dept.sejong.ac.kr/earthdpt/intro/professor.do', 'SEJONG_STANDARD'),
    ('공과대학', '에너지자원공학과', '에너지자원공학과 교수진', 'https://dept.sejong.ac.kr/energydpt/intro/professor.do', 'SEJONG_STANDARD'),
    ('공과대학', '기계공학과', '기계공학과 교수진', 'https://dept.sejong.ac.kr/medpt/intro/professor.do', 'SEJONG_STANDARD'),
    ('공과대학', '국방AI융합시스템공학과', '국방AI융합시스템공학과 교수진', 'https://dept.sejong.ac.kr/dsedpt/intro/professor.do', 'SEJONG_STANDARD'),
    ('공과대학', '나노신소재공학과', '나노신소재공학과 교수진', 'https://dept.sejong.ac.kr/nanodpt/intro/professor.do', 'SEJONG_STANDARD'),
    ('공과대학', '양자원자력공학과', '양자원자력공학과 교수진', 'https://dept.sejong.ac.kr/qnuedpt/intro/professor.do', 'SEJONG_STANDARD'),
    ('공과대학', '우주항공공학전공', '우주항공공학전공 교수진', 'https://ae.sejong.ac.kr/shop_contents/myboard_list.htm?myboard_code=professor&category_idx=82031', 'SEJONG_AEROSPACE'),
    ('공과대학', '지능형드론융합전공', '지능형드론융합전공 교수진', 'https://ae.sejong.ac.kr/shop_contents/myboard_list.htm?myboard_code=professor&category_idx=82041', 'SEJONG_AEROSPACE'),
    ('공과대학', '항공시스템공학과', '항공시스템공학과 교수진', 'https://ae.sejong.ac.kr/shop_contents/myboard_list.htm?myboard_code=professor&category_idx=82051', 'SEJONG_AEROSPACE'),
    ('경영경제대학', '경영학부', '경영학부 교수진', 'https://www.sejong.ac.kr/kor/college/school-of-business-administration.do', 'SEJONG_STANDARD'),
    ('경영경제대학', '경제학과', '경제학과 교수진', 'https://www.sejong.ac.kr/kor/college/economics.do', 'SEJONG_STANDARD'),
    ('인문과학대학', '국어국문학과', '국어국문학과 교수진', 'https://dept.sejong.ac.kr/kordpt/intro/professor.do', 'SEJONG_STANDARD'),
    ('인문과학대학', '영어데이터융합전공', '영어데이터융합전공 교수진', 'https://www.sejong.ac.kr/kor/college/english-language-and-literature.do', 'SEJONG_STANDARD'),
    ('인문과학대학', '국제일본학전공', '국제일본학전공 교수진', 'https://dept.sejong.ac.kr/jpndpt/intro/professor.do', 'SEJONG_STANDARD'),
    ('인문과학대학', '중국통상학전공', '중국통상학전공 교수진', 'https://dept.sejong.ac.kr/cndpt/intro/professor.do', 'SEJONG_STANDARD'),
    ('인문과학대학', '역사학과', '역사학과 교수진', 'https://dept.sejong.ac.kr/histdpt/intro/professor.do', 'SEJONG_STANDARD'),
    ('인문과학대학', '교육학과', '교육학과 교수진', 'https://dept.sejong.ac.kr/edudpt/intro/professor.do', 'SEJONG_STANDARD'),
    ('사회과학대학', '행정학과', '행정학과 교수진', 'https://dept.sejong.ac.kr/admdpt/intro/professor.do', 'SEJONG_STANDARD'),
    ('사회과학대학', '미디어커뮤니케이션학과', '미디어커뮤니케이션학과 교수진', 'https://dept.sejong.ac.kr/mediacomm/intro/professor.do', 'SEJONG_STANDARD'),
    ('사회과학대학', '법학과', '법학과 교수진', 'https://dept.sejong.ac.kr/law/intro/professor.do', 'SEJONG_STANDARD'),
    ('인공지능융합대학', '디자인이노베이션전공', '디자인이노베이션전공 교수진', 'https://www.sejong.ac.kr/kor/college/innovation-design-major.do', 'SEJONG_STANDARD'),
    ('인공지능융합대학', '만화애니메이션텍전공', '만화애니메이션텍전공 교수진', 'https://www.sejong.ac.kr/kor/college/cartoon-animation-technology-major.do', 'SEJONG_STANDARD'),
    ('호텔관광대학', '호텔관광경영학전공', '호텔관광경영학전공 교수진', 'https://dept.sejong.ac.kr/hoteldpt/intro/professor.do', 'SEJONG_STANDARD'),
    ('호텔관광대학', '외식경영학전공', '외식경영학전공 교수진', 'https://dept.sejong.ac.kr/cookdpt/intro/professor.do', 'SEJONG_STANDARD'),
    ('호텔관광대학', '조리서비스경영학과', '조리서비스경영학과 교수진', 'https://www.sejong.ac.kr/kor/college/global-culinary-art-pastry.do', 'SEJONG_STANDARD'),
    ('호텔관광대학', '호텔외식관광프랜차이즈경영학과', '호텔외식관광프랜차이즈경영학과 교수진', 'https://www.sejong.ac.kr/kor/college/franchise-management-and-hotel-restaurant-and-tourism.do', 'SEJONG_STANDARD'),
    ('호텔관광대학', '호텔외식비즈니스학과', '호텔외식비즈니스학과 교수진', 'https://www.sejong.ac.kr/kor/college/hotel-restaurant-business.do', 'SEJONG_STANDARD');

INSERT INTO v44_catalog_professor (record_key, college_name, department_name, professor_name, email, position, laboratory_name, website_url, description)
VALUES
    (1, '인공지능융합대학', 'AI융합전자공학과', '임준석', 'jslim@sejong.ac.kr', '교수', '임준석 교수님 연구실', 'https://prof.sejong.ac.kr/jslim/', '신호처리, 수중음향, 통신신호처리'),
    (2, '인공지능융합대학', 'AI융합전자공학과', '이준호', 'joonhlee@sejong.ac.kr', '교수', '이준호 교수님 연구실', NULL, '레이더 신호처리 배열 신호처리 통계 신호처리 해석적 성능분석 레이더 및 전자전 M&S 레이더 탐지 및 인식 알고리즘'),
    (3, '인공지능융합대학', 'AI융합전자공학과', '김동호', 'dongkim@sejong.ac.kr', '교수', '김동호 교수님 연구실', 'https://prof.sejong.ac.kr/dongkim/index.do', '차세대 안테나 전자파 잔향실 메타 물질 지능형 산란체 전자장 이론'),
    (4, '공과대학', '건축공학과', '정광복', 'kbjeong7@sejong.ac.kr', '부교수', '정광복 교수님 연구실', 'https://home.sejong.ac.kr/~hsscm/', '스마트&지속가능한 건설관리, AI 기반 의사결정시스템, 건설작업로봇'),
    (5, '공과대학', '건축공학과', '이재홍', 'jhlee@sejong.ac.kr', '교수', '이재홍 교수님 연구실', NULL, '건축분야 AI응용, 전산역학'),
    (6, '공과대학', '건축공학과', '최안섭', 'aschoi@sejong.ac.kr', '교수', '최안섭 교수님 연구실', 'https://prof.sejong.ac.kr/aschoi', 'Lighting Control Systems Daylight Responsive Dimming Systems Lighting Calculation Advanced Lighting System Modeling and Visualization Energy Efficient Lighting Systems Daylighting Design & Analysis Illumination Engineering Building Control Systems Indoor & Outdoor Lighting Design'),
    (7, '공과대학', '건축공학과', '이기학', 'kihaklee@sejong.ac.kr', '교수', '이기학 교수님 연구실', 'http://prof.sejong.ac.kr/kihaklee', '내진공학, 철근콘크리트구조, UHPC구조, 합성구조'),
    (8, '공과대학', '건축공학과', '이재욱', 'jaewook@sejong.ac.kr', '교수', '이재욱 교수님 연구실', 'https://prof.sejong.ac.kr/jaewook', '- 인공지능 기반 건축 설계 및 시공 - 건축 정보 모델링 (BIM) - 건설 관리 및 자동화 - 지능형 건물 - 설계 협업 - 스마트 시티'),
    (9, '공과대학', '건축공학과', '성민기', 'mksung@sejong.ac.kr', '교수', '성민기 교수님 연구실', 'https://sites.google.com/view/aeerl', '온열 및 공기환경 모델링 및 제어, 공기감염 확산 제어 기술, 실내 미생물오염 제어 기술, 환기/공조설비'),
    (10, '공과대학', '건축공학과', '이동규', 'dongkyulee@sejong.ac.kr', '교수', '이동규 교수님 연구실', 'https://home.sejong.ac.kr/~dongkyulee/', '- 위상최적화 - 건축 디지털 디자인 및 제조 - 딥러닝 기반 InnovilTOP 사용자 기반 앱 - 비선형 전산 구조 역학 - 생체모방 - 자가지지, 매달린, 전개 구조 - 고성능 철골구조 - 프리캐스트 더블월, 모듈러 합성 - 초고층 구조 - 수직농장 구조 디자인 - 이동식비계, 가설시스템 - 트리즈, 6시그마 특허기반 연구'),
    (11, '공과대학', '건축공학과', '안윤규', 'yunkyuan@sejong.ac.kr', '교수', '안윤규 교수님 연구실', 'http://www.ssai-lab.com/', '스마트구조 및 인공지능, 구조물 건전도 모니터링, 비파괴 검사, 구조 동역학'),
    (12, '공과대학', '건축공학과', '이승혜', 'seunghye@sejong.ac.kr', '부교수', '이승혜 교수님 연구실', 'https://aise.sejong.ac.kr/', 'AI기반 대체 구조해석기술 / AI기반 자동 구조설계기술 개발 / AI기반 건설로봇 운영기술 개발 /'),
    (13, '공과대학', '건축공학과', '김학평', 'hpkim@sejong.ac.kr', '조교수', '김학평 교수님 연구실', NULL, '건설관리, 지속가능한 건축, 건물 자동화, 감성 컴퓨팅, 인체안전공학, 건설로봇'),
    (14, '공과대학', '건축공학과', 'Tan Ngoc NGUYEN', 'tnnguyen@sejong.ac.kr', '부교수', 'Tan Ngoc NGUYEN 교수님 연구실', 'https://prof.sejong.ac.kr/tnnguyen/index.do', '구조 공학; 계산 역학; 인공 지능'),
    (15, '공과대학', '건축학과', '김영욱', 'yokim@sejong.ac.kr', '교수', '김영욱 교수님 연구실', 'http://www.spacesyntax.kr', 'Space Syntax, 건축계획 및 도시설계'),
    (16, '공과대학', '건축학과', '김한수', 'hskim@sejong.ac.kr', '교수', '김한수 교수님 연구실', 'https://home.sejong.ac.kr/~hskim/', '건설관리, 사업비관리, 건설산업혁신'),
    (17, '공과대학', '건축학과', '정성원', 'swjung@sejong.ac.kr', '교수', '정성원 교수님 연구실', 'https://prof.sejong.ac.kr/swjung', '도시건축설계, 셉테드(CPTED)'),
    (18, '공과대학', '건축학과', '권준범', 'joonkwun@sejong.ac.kr', '교수', '권준범 교수님 연구실', NULL, '건축계획 및 설계'),
    (19, '공과대학', '건축학과', '김동현', 'dkim@sejong.ac.kr', '교수', '김동현 교수님 연구실', 'https://www.dklab.co.kr', '1. 건축계획 및 설계 : 통합설계 및 건축실무 : 재료와 디테일 2. BIM(정보 모델링) : 디지털 도면 : AI 기반 설계자동화 3. 건축물 3D 프린팅 : 친환경 외피 제작(FABRICATION)'),
    (20, '공과대학', '건축학과', '정봉찬', 'bjeong@sejong.ac.kr', '조교수', '정봉찬 교수님 연구실', 'https://prof.sejong.ac.kr/bjeong', '· 온열쾌적 · 재실자 행태 · 개인 쾌적 모델 · 재실자 중심 제어 · 건물에너지'),
    (21, '공과대학', '건설환경공학과', '진승섭', 'seungsab@sejong.ac.kr', '조교수', '진승섭 교수님 연구실', NULL, '건설분야의 지식을 토대로 다양한 데이터(정보)에 대한 분석/예측/의사결정을 위한 디지털 혁신 기술(데이터 과학)과의 융합을 통한 건설 인프라 융합 기술을 개발하고 있습니다.이를 통해 설계/시공/유지관리 분야에서 지속적으로 생성되는 데이터에 대한 효율적인 분석 자동화 및 모델링에 관한 연구를 수행하여 새로운 미래건설기술을 개발하는데 집중하고 있습니다.'),
    (22, '공과대학', '건설환경공학과', '이창훈', 'clee@sejong.ac.kr', '교수', '이창훈 교수님 연구실', NULL, NULL),
    (23, '공과대학', '건설환경공학과', '이현종', 'hlee@sejong.ac.kr', '교수', '이현종 교수님 연구실', NULL, '건설-도로분야'),
    (24, '공과대학', '건설환경공학과', '송지현', 'songjh@sejong.ac.kr', '교수', '송지현 교수님 연구실', NULL, '환경공학, 대기오염관리, 휘발성유기화합물, 악취, 온실가스, 폐기물저감'),
    (25, '공과대학', '건설환경공학과', '이종재', 'jongjae@sejong.ac.kr', '교수', '이종재 교수님 연구실', NULL, '스마트 구조 시스템'),
    (26, '공과대학', '건설환경공학과', '맹승규', 'smaeng@sejong.ac.kr', '교수', '맹승규 교수님 연구실', 'https://home.sejong.ac.kr/~smaeng/', '- 수돗물 공급에서의 수질 변화연구 (유기물 특성 분석과 거동) - 먹는물에서의 생물학적 안정성 (미생물 증식 연구) 연구 - 자연형 수처리 연구 (강변여과, 인공함양, 복류수 등)'),
    (27, '공과대학', '건설환경공학과', '정일문', 'imchung@sejong.ac.kr', '교수', '정일문 교수님 연구실', 'https://orcid.org/0000-0003-0163-7305', '응용수자원공학, 지하수 수문학, 지표수-지하수 연계해석, 유역수문모델링, 기후변화와 수자원, 가뭄 및 갈수해석, 통합물관리, 지하수저류댐 및 샌드댐, AI 기반 수문예측'),
    (28, '공과대학', '건설환경공학과', '우동국', 'dkwoo@sejong.ac.kr', '부교수', '우동국 교수님 연구실', 'https://dongkookwoo.wixsite.com/mysite', '수문학, 수자원공학'),
    (29, '공과대학', '건설환경공학과', '김종민', 'jongmin@sejong.ac.kr', '조교수', '김종민 교수님 연구실', NULL, NULL),
    (30, '공과대학', '건설환경공학과', '김정호', 'junghokim@sejong.ac.kr', '조교수', '김정호 교수님 연구실', 'https://reliabilitylab.wordpress.com/', '구조신뢰성, 지진공학, 구조최적화, 복합재해, 재난 레질리언스, 대리모델, 머신러닝, AI기술'),
    (31, '공과대학', '건설환경공학과', '장대익', 'jang_daeik@sejong.ac.kr', '조교수', '장대익 교수님 연구실', NULL, '다기능-고성능 건설 재료, 스마트 재료 및 구조, 에너지 하베스팅 및 저장 시스템, 지속가능 친환경 건설 재료, 비파괴 검사'),
    (32, '공과대학', '건설환경공학과', 'Duc Kien Thai', 'thaiduckien@sejong.ac.kr', '부교수', 'Duc Kien Thai 교수님 연구실', 'https://home.sejong.ac.kr/~thaiduckien/', 'ASA (Advanced Structural Analysis) Lab은 충격, 폭발, 지진 하중 등과 같은 극한 하중을 받는 구조물의 고급 수치 시뮬레이션, 기계적 및 구조적 거동 분석에 초점을 맞춥니다. 이를 기반으로 구조에 대한 안전성 평가를 수행하고 실제 적용을 위한 새로운 솔루션 또는 구조를 제안한다. 또한 특정 하중 조건에서 구조물의 저항력을 분석하고 예측하는 토목 공학에서의 AI 적용에도 관심이 있다.'),
    (33, '공과대학', '건설환경공학과', '김상엽', 'sangyeob.kim29@sejong.ac.kr', '조교수', '김상엽 교수님 연구실', NULL, '하폐수 내 산소 전달, 산업폐수 고도처리, 정수 및 하폐수 처리공학, 막 기반 수처리 공학, 강변여과, 수처리 공정–정책 연계 연구'),
    (34, '공과대학', '건설환경공학과', '배덕효', 'dhbae@sejong.ac.kr', '석좌교수', '배덕효 교수님 연구실', NULL, '기상-수문연계 해석, 기후변화 수자원 적응, 실시간 홍수예보, 실시간 가뭄예측, 레이더강수-수문활용'),
    (35, '공과대학', '환경융합공학과', '정슬기', 'sjeong@sejong.ac.kr', '부교수', '정슬기 교수님 연구실', 'https://prof.sejong.ac.kr/sjeong/index.do', '1. 토양 및 지하수 오염 관리 기술 개발 2. 생명공학적 기법을 활용한 지속가능한 환경관리: 환경미생물 응용 기술'),
    (36, '공과대학', '환경융합공학과', '허진', 'jinhur@sejong.ac.kr', '교수', '허진 교수님 연구실', 'https://scholar.google.com/citations?user=cwte5IIAAAAJ&hl=en', '머신러닝 기반 상수원 수질관리 및 모니터링 자연유기물질 분석 및 응용 미세플라스틱 유래 용존 유기물질 물리화학적 상수처리 인위적 오염에 의한 탄소순환 교란'),
    (37, '공과대학', '환경융합공학과', '조진우', 'jinwoocho@sejong.ac.kr', '교수', '조진우 교수님 연구실', 'https://home.sejong.ac.kr/~jinwoocho/', '하폐수고도처리, 분리막 이용 수처리, 막증발법 이용 담수화, 폐자원 바이오가스화, 수처리시스템 최적화 및 개발'),
    (38, '공과대학', '환경융합공학과', '홍성욱', 'sesttiya@sejong.ac.kr', '교수', '홍성욱 교수님 연구실', 'https://scholar.google.com/citations?hl=en&user=6BH8BdAAAAAJ&view_op=list_works&sortby=pubdate', 'ㅇ 원격탐사 - 환경, 대기, 기상, 해양, 극지, 육상, 농산림, 재난재해, 기후변화 ㅇ 인공지능 활용'),
    (39, '공과대학', '환경융합공학과', '정지훈', 'jjeehoon@sejong.ac.kr', '교수', '정지훈 교수님 연구실', 'https://prof.sejong.ac.kr/jjeehoon/index.do', '기후역학, 기후모델링, 기후예측, 극한기후현상, 지면대기 상호작용'),
    (40, '공과대학', '환경융합공학과', '노준성', 'junsungsea@sejong.ac.kr', '부교수', '노준성 교수님 연구실', NULL, '해양생태 기후변화적응 연구실 1. 해양생태계 구조 및 기능: 서식생물 구조 및 기능(먹이망), 생태계/환경영향평가(생물영향실험) 2. 해양생태계 기후변화적응: 탄소흡수력(블루카본), 인공생태계 실험(실내/실외 메조코즘, 아쿠아포닉스)'),
    (41, '공과대학', '환경융합공학과', '이영수', 'ysl@sejong.ac.kr', '조교수', '이영수 교수님 연구실', 'https://circsj.github.io/', '청정순환기술, 인공지능 활용, 대기환경공학, 폐기물공학'),
    (42, '공과대학', '환경융합공학과', '레자니아샤하발딘', 'shahab.rezania@sejong.ac.kr', '부교수', '레자니아샤하발딘 교수님 연구실', NULL, '오염 정화 (중금속, 미세플라스틱, 잔류성 유기오염물질) 폐수 처리 (식물정화법, 흡착) 폐기물 관리 (바이오연료 등 에너지 생산)'),
    (43, '공과대학', '환경융합공학과', '이윤경', 'yunkyunglee@sejong.ac.kr', '조교수', '이윤경 교수님 연구실', 'https://prof.sejong.ac.kr/yunkyunglee/index.do', '전지구적 탄소 순환, 미세오염물질, 환경 교란, 분광 센서, 환경 모니터링'),
    (44, '공과대학', '환경융합공학과', '이인옥', 'inok@sejong.ac.kr', '조교수', '이인옥 교수님 연구실', 'https://prof.sejong.ac.kr/inok', '1) 해양생태계 구조 및 기능 연구 - 해양 생물 개체군 및 군집 반응 평가 - 해양생태계 먹이망 영양역학 연구(탄소 및 질소 안정동위원소비 활용) 2) 기후변화 대응 및 해양 환경 스마트 관리 - 스마트 시스템을 활용한 해양생태계 구조 및 기능 변화 평가'),
    (45, '공과대학', '에너지자원공학과', '배태석', 'baezae@sejong.ac.kr', '교수', '배태석 교수님 연구실', NULL, '측지/위성측위'),
    (46, '공과대학', '에너지자원공학과', '박혁진', 'hjpark@sejong.ac.kr', '교수', '박혁진 교수님 연구실', NULL, '지질공학, 지질재해, 머신러닝 기반 위험도 분석'),
    (47, '공과대학', '에너지자원공학과', '김상완', 'swkim@sejong.edu', '교수', '김상완 교수님 연구실', NULL, '원격탐사 SAR, InSAR 응용분야 자연재해 모니터링'),
    (48, '공과대학', '에너지자원공학과', '정명채', 'jmc65@sejong.ac.kr', '교수', '정명채 교수님 연구실', 'https://home.sejong.ac.kr/~jmc65/', '환경지구화학 광해방지기술 중금속 오염 토양 및 지하수 환경학'),
    (49, '공과대학', '에너지자원공학과', '남명진', 'nmj1203@sejong.ac.kr', '교수', '남명진 교수님 연구실', NULL, '물리탐사/물리검층, 이산화탄소지중저장, 기후테크, 에너지정책'),
    (50, '공과대학', '에너지자원공학과', '권경중', 'kjkwon@sejong.ac.kr', '교수', '권경중 교수님 연구실', 'https://sites.google.com/site/kyungjungkwon/', '이차전지, 재활용, 연료전지'),
    (51, '공과대학', '에너지자원공학과', '김형목', 'hmkim@sejong.ac.kr', '교수', '김형목 교수님 연구실', 'https://home.sejong.ac.kr/~hmkim/', '암석역학 및 암반공학, 에너지환경 지오메카닉스, 지하암반 내 열-수리-역학-화학 복합거동, 대용량 에너지 지하저장'),
    (52, '공과대학', '에너지자원공학과', '박상은', 'separk@sejong.ac.kr', '교수', '박상은 교수님 연구실', 'https://prof.sejong.ac.kr/separk', '인공위성 지구물리/지구정보공학, 다중편파 SAR 자료처리, SAR 자료 활용(기후변화/재해/수문/Biomass), 지구관측 정보 융합'),
    (53, '공과대학', '에너지자원공학과', '최요순', 'energy@sejong.ac.kr', '교수', '최요순 교수님 연구실', 'https://sites.google.com/view/smart-x-lab', '☀️ 지속가능한 미래를 위한 에너지 AI 기술 🚗 태양광 전기차 등 에너지–모빌리티 융합 기술 🔁 재생에너지 기반 전기차 충전 인프라 최적화 기술 🧠 AI 에이전트 기반 자율 광산 운영 기술 🤖 극한환경 대응 자율 로봇 및 피지컬 AI 기술 🛠️ 디지털 트윈 기반 시스템 최적화 기술 🌍 핵심광물 공급망 시뮬레이션 및 회복탄력성 분석 🪐 우주자원 탐사·채굴 및 에너지 활용 기술'),
    (54, '공과대학', '에너지자원공학과', '김정환', 'junghwan@sejong.ac.kr', '부교수', '김정환 교수님 연구실', 'https://prof.sejong.ac.kr/junghwan/index.do', '반도체 태양전지 광전기화학적 CO2 환원'),
    (55, '공과대학', '에너지자원공학과', '최윤정', 'yoonchoi@sejong.ac.kr', '조교수', '최윤정 교수님 연구실', NULL, '고고물리탐사, 문화재탐사, 지구물리탐사, 분광탐사'),
    (56, '공과대학', '기계공학과', '전용태', 'ytjun@sejong.ac.kr', '교수', '전용태 교수님 연구실', NULL, 'Computer-Aided Design, 스마트 설계 및 제조'),
    (57, '공과대학', '기계공학과', '이민형', 'mlee@sejong.ac.kr', '교수', '이민형 교수님 연구실', NULL, '유체역학, 전산역학, 대변형 SW 개발, 고속충돌/폭발 해석'),
    (58, '공과대학', '기계공학과', '신영기', 'ygshin@sejong.ac.kr', '교수', '신영기 교수님 연구실', NULL, '- Virtual real-time simulation of refrigeration cycle dynamics in Simulink - Online fault detection of thermal energy systems based on dynamic simulators and FDD algorithm - Optimal control of car HVAC systems based on dynamic simulation - Dynamic simulation of building energy in EnergyPlus'),
    (59, '공과대학', '기계공학과', '정재동', 'jdchung@sejong.ac.kr', '교수', '정재동 교수님 연구실', 'https://thermalengineerlab.wixsite.com/home', 'Thermal Energy Storage & Transport Desiccant Cooling & Adsorption Cooling Phase Change Nano-scale Heat Transfer'),
    (60, '공과대학', '기계공학과', '곽관웅', 'kwgwak@sejong.ac.kr', '교수', '곽관웅 교수님 연구실', 'https://prof.sejong.ac.kr/kwgwak/', 'Robotics, Controls, Mechatronics'),
    (61, '공과대학', '기계공학과', '손채훈', 'chsohn@sejong.ac.kr', '교수', '손채훈 교수님 연구실', 'https://prof.sejong.ac.kr/chsohn/index.do', '연소/추진 공학'),
    (62, '공과대학', '기계공학과', '장강원', 'gwjang@sejong.ac.kr', '교수', '장강원 교수님 연구실', 'https://home.sejong.ac.kr/~gwjang/', '최적설계 차체 저자유도 모델링 AI 기반 설계'),
    (63, '공과대학', '기계공학과', '임도형', 'dli349@sejong.ac.kr', '교수', '임도형 교수님 연구실', NULL, '생체역학 / 금속적층제조/ 의공학'),
    (64, '공과대학', '기계공학과', '정재희', 'jaehee@sejong.ac.kr', '교수', '정재희 교수님 연구실', 'http://prof.sejong.ac.kr/jaehee', '- 환경-생물학 오염 물질 측정/탐지 시스템 및 인공지능 기반 분석 알고리즘 개발 - 나노 신소재 기반 공기 및 표면 생물학 오염물질 제어 기술 개발'),
    (65, '공과대학', '기계공학과', '안건식', 'kunsik1214@sejong.ac.kr', '조교수', '안건식 교수님 연구실', 'https://sites.google.com/view/ksanlab', '로보틱스용 물리 센서 개발, 반도체/디스플레이 공정 (TFT, OLED, QLED 등), AI기반 제조공정 최적화'),
    (66, '공과대학', '기계공학과', '권보미', 'bgweon@sejong.ac.kr', '부교수', '권보미 교수님 연구실', 'https://prof.sejong.ac.kr/bgweon/index.do', '세포역학, 바이오이미징 및 측정 시스템, AI 기반 멀티모드 바이오이미지 분석'),
    (67, '공과대학', '기계공학과', 'Naseem Abbas', 'naseem.abbas@sejong.ac.kr', '조교수', 'Naseem Abbas 교수님 연구실', NULL, NULL),
    (68, '공과대학', '기계공학과', 'Shah Nehad Ali', 'nehadali199@yahoo.com', '조교수', 'Shah Nehad Ali 교수님 연구실', NULL, NULL),
    (69, '공과대학', '기계공학과', '손진우', 'jwson@sejong.ac.kr', '조교수', '손진우 교수님 연구실', NULL, '플라즈마 수치해석 기법 개발, 전기장·플라즈마 연소, 연소 및 반응유동 해석'),
    (70, '공과대학', '기계공학과', 'Gholamali Zadeh Peyman', 'peyman@sejong.ac.kr', '조교수', 'Gholamali Zadeh Peyman 교수님 연구실', 'https://prof.sejong.ac.kr/peyman', 'CO₂ 가스 흡착, 제습제 코팅 열펌프, 흡착식 냉동기, 배터리 열관리, 에너지 저장 시스템'),
    (71, '공과대학', '국방AI융합시스템공학과', '윤여선', 'ysyoon@sejong.ac.kr', '부교수', '윤여선 교수님 연구실', 'https://prof.sejong.ac.kr/ysyoon', '- 레이다 신호처리 - 배열 신호처리 - 압축 센싱 - 광대역 레이다 신호처리'),
    (72, '공과대학', '국방AI융합시스템공학과', '김은희', 'eunheekim@sejong.ac.kr', '교수', '김은희 교수님 연구실', 'https://prof.sejong.ac.kr/eunheekim', '국방 레이더 기술/ 레이더 시스템, 파형 및 신호처리 연구/ 응용분야 : 전투기용 레이다, 노이즈레이다, 차량용 레이더 등'),
    (73, '공과대학', '국방AI융합시스템공학과', '이근화', 'nasalkh2@sejong.ac.kr', '교수', '이근화 교수님 연구실', NULL, '수중음향학, 유체소음 및 방사소음, 물리기반 딥러닝 및 추정'),
    (74, '공과대학', '국방AI융합시스템공학과', '김도완', 'dwk@sejong.ac.kr', '교수', '김도완 교수님 연구실', 'https://prof.sejong.ac.kr/dwk', '비선형 제어 이론, 해양 무인이동체, 무인잠수정(AUV), 무인수상정(USV), 유도무기 체계, 무인항공기(UAV)'),
    (75, '공과대학', '국방AI융합시스템공학과', '김종혁', 'jonghoek@sejong.ac.kr', '부교수', '김종혁 교수님 연구실', NULL, '표적 추적, -로봇 공학, -신호처리, -인공지능'),
    (76, '공과대학', '국방AI융합시스템공학과', '김근환', 'kimgw200@sejong.ac.kr', '조교수', '김근환 교수님 연구실', NULL, '소나 신호처리, 기계학습 기반 표적 탐지 및 식별, 이상치 탐지'),
    (77, '공과대학', '국방AI융합시스템공학과', 'Sufyan Ali MEMON', 'sufyanahmedali@sejong.ac.kr', '조교수', 'Sufyan Ali MEMON 교수님 연구실', NULL, '안내, 탐색, 추정 및 추적'),
    (78, '공과대학', '국방AI융합시스템공학과', '김영신', 'p3ckimys@sejong.ac.kr', '초빙교수', '김영신 교수님 연구실', NULL, '해군기본교리 및 작전 전자전'),
    (79, '공과대학', '국방AI융합시스템공학과', '김현일', 'mongin21@sejong.ac.kr', '초빙교수', '김현일 교수님 연구실', NULL, '국제정치, 국가전략, 해양전략, 세력전이론, AI, 유.무인복합체'),
    (80, '공과대학', '국방AI융합시스템공학과', '유근종', 'ykj91297@sejong.ac.kr', '초빙교수', '유근종 교수님 연구실', NULL, '국방 연구개발(R&D) : 현 국방 연구개발(R&D)이 “국방획득체계의 일부인 무기체계 위주로 추진되고 있고 전력지원체계 분야는 투자가 저조하여 이를 발전시킬 수 있는 방안 고찰 및 제시'),
    (81, '공과대학', '국방AI융합시스템공학과', '김지찬', 'jichankim@sejong.ac.kr', '석좌교수', '김지찬 교수님 연구실', NULL, NULL),
    (82, '공과대학', '국방AI융합시스템공학과', '홍우영', 'wyhong@sejong.ac.kr', '석좌교수', '홍우영 교수님 연구실', 'https://prof.sejong.ac.kr/wyhong/index.do', '• 수중음향 신호처리 • 배열신호처리, • 탐지 및 추정 • 무기체계 효과도 분석'),
    (83, '공과대학', '나노신소재공학과', '정종완', 'jwjung@sejong.ac.kr', '교수', '정종완 교수님 연구실', 'https://prof.sejong.ac.kr/jwjung/index.do', '실리콘, 산화물 반도체 소자 및 공정 강유전체 소자 및 공정 연구 뉴로모픽 소자 2차원 전자 소자 에너지 소재 (배터리전극, 슈퍼커패시터 전극 )'),
    (84, '공과대학', '나노신소재공학과', '김선재', 'sjkim1@sejong.ac.kr', '교수', '김선재 교수님 연구실', 'https://sejong.elsevierpure.com/en/persons/sun-jae-kim/', '에너지생산 및 저장용 재료 합성기술 분야: 수소에너지재료, 리튬전지 등'),
    (85, '공과대학', '나노신소재공학과', '이원준', 'wjlee@sejong.ac.kr', '교수', '이원준 교수님 연구실', 'https://prof.sejong.ac.kr/wjlee/', '반도체 제조용 공정/소재/장비의 연구개발 - Atomic layer deposition (ALD) and etching (ALE) - precursors, in situ analysis, DFT simulation - 3D packaging - hybrid bonding, FEM simulation'),
    (86, '공과대학', '나노신소재공학과', '이원희', 'whlee@sejong.ac.kr', '교수', '이원희 교수님 연구실', NULL, 'Materials processing development Powder metallurgy Nano-structures materials Biomaterials Surface modification'),
    (87, '공과대학', '나노신소재공학과', '이내성', 'nslee@sejong.ac.kr', '교수', '이내성 교수님 연구실', 'https://prof.sejong.ac.kr/nslee/index.do', '• CVD 및 전기방전을 이용한 고결정 CNT 합성 연구 • 엑스선 튜브, UV 램프 및 여러 전자빔 응용을 위한 CNT 페이스트 기반의 전계방출 에미터 연구 • 이차전지 양극 및 음극 전도성 첨가재용 SWCNT의 친환경 기상정제 기술 연구 • 탄소나노소재를 이용한 열전도성 복합소재 연구 • 탄소나노소재를 이용한 유연 투명 박막히터 및 투명전극 연구'),
    (88, '공과대학', '나노신소재공학과', '홍성철', 'sunghong@sejong.ac.kr', '교수', '홍성철 교수님 연구실', 'https://prof.sejong.ac.kr/sunghong', '고분자'),
    (89, '공과대학', '나노신소재공학과', '김기범', 'kbkim@sejong.ac.kr', '교수', '김기범 교수님 연구실', 'https://prof.sejong.ac.kr/kbkim/index.do', '합금설계, 미세조직제어, 기계적 특성, 표면기능화'),
    (90, '공과대학', '나노신소재공학과', '서용호', 'yseo@sejong.ac.kr', '교수', '서용호 교수님 연구실', 'https://prof.sejong.ac.kr/yseo', 'AI 기반 반도체 장비 개발 나노소자 개발 및 나노 측정 제어 나노 제어 연구 장비 개발'),
    (91, '공과대학', '나노신소재공학과', '서영수', 'ysseo@sejong.ac.kr', '교수', '서영수 교수님 연구실', 'https://prof.sejong.ac.kr/ysseo/index.do', '1. Cellulose nanofibril (CNF) : Surface modifications, Dispersion, Polymer composite 2. Quantum dot encapsulation : Polymeric and Silica encapsulation for QD display and Bio-sensor 3. Nanotubes and graphene oxide : CNT and BNNT dispersion for thermal dissipating materials etc 4. Gas separation membrane'),
    (92, '공과대학', '나노신소재공학과', '박준영', 'jyoung@sejong.ac.kr', '교수', '박준영 교수님 연구실', 'https://prof.sejong.ac.kr/jyoung', '연료전지, 전고체전지, 수전해전지, 가스센서, 가스분리막, 수소촉매'),
    (93, '공과대학', '나노신소재공학과', '최택집', 'tjchoi@sejong.ac.kr', '교수', '최택집 교수님 연구실', 'https://www.needs-laboratory.com/', '뉴로모픽소재/소자, 강유전체 메모리, 태양광 물분해 전지, 메타결합센서, 차세대 메모리 소재/소자, 양자소재, 저차원소재'),
    (94, '공과대학', '나노신소재공학과', '명승택', 'smyung@sejong.ac.kr', '교수', '명승택 교수님 연구실', 'https://smyung.wixsite.com/abml', '리튬이온이차전지'),
    (95, '공과대학', '나노신소재공학과', '손기선', 'kssohn@sejong.ac.kr', '교수', '손기선 교수님 연구실', 'https://www.ssehub-aimaterialslab.kr/', '인공지능을 이용한 에너지 소재 개발'),
    (96, '공과대학', '나노신소재공학과', '최영진', 'jini38@sejong.ac.kr', '교수', '최영진 교수님 연구실', 'https://prof.sejong.ac.kr/jini38', '나노 반도체 소재 기반 광전자 소자'),
    (97, '공과대학', '나노신소재공학과', '허광', 'kheo@sejong.ac.kr', '교수', '허광 교수님 연구실', 'https://kheo2001.wixsite.com/nbhm', '나노바이오 복합 구조 개발, 바이오 센서, 바이오 압전소자, 적층구조 등.'),
    (98, '공과대학', '나노신소재공학과', '김태완', 'twkim@sejong.ac.kr', '부교수', '김태완 교수님 연구실', NULL, NULL),
    (99, '공과대학', '나노신소재공학과', '김성규', 'sungkyu@sejong.ac.kr', '부교수', '김성규 교수님 연구실', 'https://sungkyukim.wixsite.com/sungkyu', '차세대반도체, 뉴로모픽 소자, 리모트 에피택시, 실시간 원자단위 거동 분석'),
    (100, '공과대학', '나노신소재공학과', '송희조', 'hjsong@sejong.ac.kr', '부교수', '송희조 교수님 연구실', 'https://prof.sejong.ac.kr/hjsong/', '재료공학, 나노재료, 에너지재료, 전기촉매, 수소, 암모니아'),
    (101, '공과대학', '나노신소재공학과', '정미희', 'mhjung@sejong.ac.kr', '부교수', '정미희 교수님 연구실', NULL, NULL),
    (102, '공과대학', '나노신소재공학과', '홍성환', 'shhong@sejong.ac.kr', '부교수', '홍성환 교수님 연구실', NULL, '고기능성 구조재료, 초탄성합금, 벌크비정질합금, 형상기억합금, 타이타늄합금, 고엔트로피합금, 컬러합금'),
    (103, '공과대학', '나노신소재공학과', 'Sajjad Hussain', 'hussain@sejong.ac.kr', '부교수', 'Sajjad Hussain 교수님 연구실', NULL, NULL),
    (104, '공과대학', '나노신소재공학과', '알카심모삽', 'mosabkaseem@sejong.ac.kr', '부교수', '알카심모삽 교수님 연구실', 'https://prof.sejong.ac.kr/mosabkaseem', '플라즈마 전해 산화를 이용한 금속 소재의 표면개질 및 내식 코팅 유무기 복합 코팅 기반 기능성 표면 설계 전기화학적 분석 및 등가회로 모델 해석 광촉매 및 생체활성 금속 코팅 개발'),
    (105, '공과대학', '나노신소재공학과', 'PATIL SUPRIYA ALIAS SUREKHA ANKUSH', 'supriya2812@sejong.ac.kr', '부교수', 'PATIL SUPRIYA ALIAS SUREKHA ANKUSH 교수님 연구실', NULL, NULL),
    (106, '공과대학', '나노신소재공학과', '이동기', 'tongki7@sejong.ac.kr', '조교수', '이동기 교수님 연구실', NULL, '유/무기 나노구조 반도체 여기 상태 분석'),
    (107, '공과대학', '나노신소재공학과', 'Natalia Vyacheslavovna VORONINA', 'voronina@sejong.ac.kr', '조교수', 'Natalia Vyacheslavovna VORONINA 교수님 연구실', NULL, NULL),
    (108, '공과대학', '나노신소재공학과', '양현우', 'hwyang@sejong.ac.kr', '조교수', '양현우 교수님 연구실', 'https://sejong.elsevierpure.com/en/persons/hyeon-woo-yang/', '이차전지, 에너지 저장 재료, 음극, 고체전해질, 고체전해질계면층'),
    (109, '공과대학', '나노신소재공학과', 'Nazir Ghazanfar', 'gnazir@sejong.ac.kr', '조교수', 'Nazir Ghazanfar 교수님 연구실', NULL, '마이크로 및 나노 장치 제작, Spintronic 장치(Gr/TMD 이종 구조), 전하 밀도 파동(CDW), p-n 및 p-i-n 다이오드, 광검출기, 메모리 장치, 태양 전지, 전산 응축 물질 물리학, 가스 저장(예: CO2, H2, 등), 슈퍼커패시터 및 산화환원 배터리 .'),
    (110, '공과대학', '나노신소재공학과', 'SUNIL KUMAR', 'skumar@sejong.ac.kr', '조교수', 'SUNIL KUMAR 교수님 연구실', 'https://prof.sejong.ac.kr/skumar', NULL),
    (111, '공과대학', '나노신소재공학과', '박혜진', 'haejinp@sejong.ac.kr', '조교수', '박혜진 교수님 연구실', 'https://sejong.elsevierpure.com/en/persons/hae-jin-park/', '다성분계 합금 설계, 금속 박막 개발 및 물성 최적화, 표면 나노 구조화, 기능성 산화물 성장 거동 규명, 미세조직 및 상변태 제어, 기계적 특성 최적화'),
    (112, '공과대학', '나노신소재공학과', 'Abbas Haider', 'haider@sejong.ac.kr', '조교수', 'Abbas Haider 교수님 연구실', 'https://prof.sejong.ac.kr/haider', '나노전자 장치, 신흥 반도체 소자, AI용 하드웨어, 멤리스터, 뉴로모픽 컴퓨팅, 차세대메모리기술'),
    (113, '공과대학', '나노신소재공학과', '박경순', NULL, '대우교수', '박경순 교수님 연구실', NULL, NULL),
    (114, '공과대학', '양자원자력공학과', '박창제', 'parkcj@sejong.ac.kr', '교수', '박창제 교수님 연구실', 'https://prof.sejong.ac.kr/parkcj', '원자로 해석 및 노심 설계'),
    (115, '공과대학', '양자원자력공학과', '정해용', 'hyjeong@sejong.ac.kr', '교수', '정해용 교수님 연구실', NULL, '원자로 열수력 및 안전성 평가'),
    (116, '공과대학', '양자원자력공학과', '정우식', 'woosjung@sejong.ac.kr', '교수', '정우식 교수님 연구실', NULL, '원전의 확률론적안전성평가 및 물리적 방호'),
    (117, '공과대학', '양자원자력공학과', '김종성', 'kimjsbat@sejong.ac.kr', '교수', '김종성 교수님 연구실', NULL, '- 설계기준 초과 지진 하 구조 건전성 평가 - 원자로 구성품 응력부식균열 성장 평가 - 원자력발전소 용접부의 잔류응력 및 파괴 분석 - 사용후핵연료 저장조 및 운반용기 건전성 평가'),
    (118, '공과대학', '양자원자력공학과', '임경택', 'kl2548@sejong.ac.kr', '부교수', '임경택 교수님 연구실', 'https://qnue.sejong.ac.kr/research/laboratory', '방사선 계측시스템, 방사선 선량평가, 핵비확산 규제'),
    (119, '공과대학', '양자원자력공학과', '이연건', 'yglee@sejong.ac.kr', '부교수', '이연건 교수님 연구실', 'https://ygfamily.creatorlink.net/', '2상 유동, 상변화 열전달, 열수력 안전해석'),
    (120, '공과대학', '양자원자력공학과', 'Nguyen Huu Tiep', 'tiepngh@sejong.ac.kr', '조교수', 'Nguyen Huu Tiep 교수님 연구실', 'https://prof.sejong.ac.kr/tiepngh/', '열수력학, 원자로 물리학, 자료 동화 머신러닝, 불확실성 정량화.'),
    (121, '공과대학', '양자원자력공학과', '홍석표', 'seokpyo.hong@sejong.ac.kr', '조교수', '홍석표 교수님 연구실', 'https://sml.sejong.ac.kr/', '배관 시스템 파괴 역학 및 안전성 평가, 스테인리스강 접합 및 표면 처리 공정, 원자력 기기 재료 파손 거동 해석'),
    (122, '공과대학', '우주항공공학전공', '홍성경', 'skhong@sejong.ac.kr', '전임교원', '홍성경 교수님 연구실', NULL, '수직이착륙기 제어, 고장 허용 제어, 군집/편대 비행, HILS'),
    (123, '공과대학', '우주항공공학전공', '안존', 'jonahn@sejong.ac.kr', '전임교원', '안존 교수님 연구실', NULL, 'Aerospace System Design, Propulsion & Energy Conversion : Gas Turbine, Jet Engine, Propeller, Rocket Aerodynamic Design : UAV / MAV / UAM / V-TOL, CFD, Solar UAV / Human Powered Aircrafts'),
    (124, '공과대학', '우주항공공학전공', '박성수', 'sungsu@sejong.ac.kr', '전임교원', '박성수 교수님 연구실', NULL, '유도제어'),
    (125, '공과대학', '우주항공공학전공', '김해동', 'haedong@sejong.ac.kr', '전임교원', '김해동 교수님 연구실', NULL, '전산 유체, 시뮬레이션'),
    (126, '공과대학', '우주항공공학전공', '박병운', 'byungwoon@sejong.ac.kr', '전임교원', '박병운 교수님 연구실', NULL, '위성항법'),
    (127, '공과대학', '우주항공공학전공', '이균호', 'khlee0406@sejong.ac.kr', '전임교원', '이균호 교수님 연구실', NULL, '우주항공추진, 열/유체/연소공학, 전산유체역학, 인공위성시스템 공학'),
    (128, '공과대학', '우주항공공학전공', '김재강', 'jaegkim@sejong.ac.kr', '전임교원', '김재강 교수님 연구실', NULL, '우주 및 행성 재진입역학'),
    (129, '공과대학', '우주항공공학전공', '이성섭', 'spacein0320@sejong.ac.kr', '전임교원', '이성섭 교수님 연구실', NULL, '군집위성, 궤도공학'),
    (130, '공과대학', '우주항공공학전공', '김오종', 'ojong@sejong.ac.kr', '전임교원', '김오종 교수님 연구실', NULL, '초소형위성시스템, 항법시스템'),
    (131, '공과대학', '우주항공공학전공', '유호준', 'hojun.you@sejong.ac.kr', '전임교원', '유호준 교수님 연구실', NULL, 'Computational Fluid Dynamics, Numerical Analysis, High-performance Computing, Hypersonic Aerothermodynamics'),
    (132, '공과대학', '우주항공공학전공', '조병운', 'bjo@sejong.ac.kr', '전임교원', '조병운 교수님 연구실', NULL, '유도제어, 시스템설계 및 최적화, 비행 및 궤도역학, 우주위험감시'),
    (133, '공과대학', '우주항공공학전공', '심한슬', 'hshim12@sejong.ac.kr', '전임교원', '심한슬 교수님 연구실', NULL, 'Optical Flow Diagnostics, Hypersonic Flows, Combustion, Real-Environment Applications'),
    (134, '공과대학', '우주항공공학전공', '김정현', 'junghyun.kim@sejong.ac.kr', '전임교원', '김정현 교수님 연구실', NULL, 'Machine Learning, Optimization, Systems Design, Air Traffic Management'),
    (135, '공과대학', '우주항공공학전공', 'NGUYEN Xuan Mung', 'xuanmung@sejong.ac.kr', '연구중점전임교원', 'NGUYEN Xuan Mung 교수님 연구실', NULL, '항공우주공학'),
    (136, '공과대학', '우주항공공학전공', '김인녕', 'innyoungkim@sejong.ac.kr', '전임교원', '김인녕 교수님 연구실', NULL, '전산유체역학, 다중물리 시뮬레이션, 인공지능(강화학습, 딥러닝), 설계 최적화, 제어'),
    (137, '공과대학', '지능형드론융합전공', '강승훈', 'shkang@sejong.ac.kr', '전임교원', '강승훈 교수님 연구실', NULL, '항공우주 구조 및 재료, 전산 구조 역학, 다물체 동역학, 구조 설계'),
    (138, '공과대학', '지능형드론융합전공', '신희석', 'hsshin9017@sejong.ac.kr', '연구중점전임교원', '신희석 교수님 연구실', NULL, 'Control and path planning of autonomous vehicle, Autonomous of Tractor-trailer system'),
    (139, '공과대학', '지능형드론융합전공', 'Tran Huy Hung', 'huyhung@sejong.ac.kr', '연구중점전임교원', 'Tran Huy Hung 교수님 연구실', NULL, 'Antenna Design, Microwave Circuit'),
    (140, '공과대학', '항공시스템공학과', 'PETHA SETHURAMAN Vignesh Ram', 'rampsv@sejong.ac.kr', '연구중점전임교원', 'PETHA SETHURAMAN Vignesh Ram 교수님 연구실', NULL, '기계공학'),
    (141, '공과대학', '항공시스템공학과', '김대중', 'sonodjk@sejong.ac.kr', '비전임교원', '김대중 교수님 연구실', NULL, '항공공학'),
    (142, '공과대학', '항공시스템공학과', '최성천', 'scchoi@sejong.ac.kr', '비전임교원', '최성천 교수님 연구실', NULL, '항공공학'),
    (143, '공과대학', '항공시스템공학과', '이성용', 'apex01@sejong.ac.kr', '비전임교원', '이성용 교수님 연구실', NULL, NULL),
    (144, '공과대학', '항공시스템공학과', '박한주', 'poi0507@sejong.ac.kr', '비전임교원', '박한주 교수님 연구실', NULL, '경영학'),
    (145, '공과대학', '항공시스템공학과', '전현석', 'ewmann@sejong.ac.kr', '산학협력중점교수', '전현석 교수님 연구실', NULL, '우주학'),
    (146, '경영경제대학', '경영학부', '이재원', 'jaywonlee@sejong.ac.kr', '교수', '이재원 교수님 연구실', NULL, '재무회계, 가치평가, 스타트업, 블록체인'),
    (147, '경영경제대학', '경영학부', '이상재', 'sangjae@sejong.ac.kr', '교수', '이상재 교수님 연구실', NULL, '데이터마이닝기법을 이용한 비즈니스 애널리틱스 사이버 보안관리 최신정보시스템에 대한 평가, 계획, 관리'),
    (148, '경영경제대학', '경영학부', '권인수', 'kwonis@sejong.ac.kr', '교수', '권인수 교수님 연구실', NULL, '리더십, 잡 크래프팅, 능동적 행동'),
    (149, '경영경제대학', '경영학부', '이동일', 'donlee@sejong.ac.kr', '교수', '이동일 교수님 연구실', NULL, '온라인 경로관리, 온라인 경로 촉진, 온라인 소비자 행동'),
    (150, '경영경제대학', '경영학부', '김준석', 'jskim@sejong.ac.kr', '교수', '김준석 교수님 연구실', NULL, '생산운영관리, 재고관리, 구매관리, 공급사슬관리'),
    (151, '경영경제대학', '경영학부', '우종필', 'yujongpil@sejong.ac.kr', '교수', '우종필 교수님 연구실', NULL, '빅데이터 & 인공지능 마케팅'),
    (152, '경영경제대학', '경영학부', '최진호', 'jhchoi@sejong.ac.kr', '교수', '최진호 교수님 연구실', NULL, NULL),
    (153, '경영경제대학', '경영학부', '황용식', 'yhwang@sejong.ac.kr', '교수', '황용식 교수님 연구실', NULL, '전략경영/국제경영/항공경영'),
    (154, '경영경제대학', '경영학부', '강원', 'kangwon@sejong.ac.kr', '교수', '강원 교수님 연구실', NULL, NULL),
    (155, '경영경제대학', '경영학부', '김지헌', 'jihern@sejong.ac.kr', '교수', '김지헌 교수님 연구실', NULL, '마케팅(소비자 심리, 브랜드 전략)'),
    (156, '경영경제대학', '경영학부', '이창섭', 'crhee2@sejong.ac.kr', '교수', '이창섭 교수님 연구실', 'https://home.sejong.ac.kr/~accounting/', '회계학'),
    (157, '경영경제대학', '경영학부', '이지훈', 'petra@sejong.ac.kr', '교수', '이지훈 교수님 연구실', NULL, '경제학 산업조직론 산업 연구: 서비스 정보/인터넷 서비스'),
    (158, '경영경제대학', '경영학부', '이규석', 'kyuseoklee@sejong.ac.kr', '교수', '이규석 교수님 연구실', NULL, '투자, 국제재무'),
    (159, '경영경제대학', '경영학부', '허재영', 'jayhuh@sejong.ac.kr', '교수', '허재영 교수님 연구실', 'https://home.sejong.ac.kr/~jayhuh', '핀테크, AI & Data 분석, 신용 & 리스크 관리'),
    (160, '경영경제대학', '경영학부', '전병조', 'bionjochun@sejong.ac.kr', '교수', '전병조 교수님 연구실', NULL, NULL),
    (161, '경영경제대학', '경영학부', '김혜진', 'haejinkim@sejong.ac.kr', '부교수', '김혜진 교수님 연구실', NULL, '인적자원관리, 노사관계'),
    (162, '경영경제대학', '경영학부', '윤혜정', 'hjyoon@sejong.ac.kr', '부교수', '윤혜정 교수님 연구실', NULL, '- 직원창의성 - 위기 및 변화관리 - 조직공정성 - 개인성격과 조직 간 적합도'),
    (163, '경영경제대학', '경영학부', '윤호정', 'hjan335@sejong.ac.kr', '부교수', '윤호정 교수님 연구실', NULL, NULL),
    (164, '경영경제대학', '경영학부', '선우희연', 'hysunwoo@sejong.ac.kr', '부교수', '선우희연 교수님 연구실', 'https://prof.sejong.ac.kr/hysunwoo', '세무회계, 재무회계, 회계감사, 지속가능성정보'),
    (165, '경영경제대학', '경영학부', '정혜진', 'hj-chung@sejong.ac.kr', '부교수', '정혜진 교수님 연구실', NULL, NULL),
    (166, '경영경제대학', '경영학부', '이희수', 'heesoo@sejong.ac.kr', '부교수', '이희수 교수님 연구실', 'https://prof.sejong.ac.kr/heesoo', '헤지펀드, 금융위험관리, 시장위험전염, 시장의 네트워크'),
    (167, '경영경제대학', '경영학부', '양승희', 'shyang0124@sejong.ac.kr', '부교수', '양승희 교수님 연구실', 'https://prof.sejong.ac.kr/shyang0124', '무형자산의 인식 및 측정, 연구개발비 자본화, 회계정보의 유용성'),
    (168, '경영경제대학', '경영학부', 'SHIN NINA', 'ninashin@sejong.ac.kr', '부교수', 'SHIN NINA 교수님 연구실', 'https://prof.sejong.ac.kr/ninashin', '디지털 운영 및 거버넌스, 지속가능 운영 및 성과관리, 서비스 운영 및 디지털 전환'),
    (169, '경영경제대학', '경영학부', '류상희', 'sryu@sejong.ac.kr', '부교수', '류상희 교수님 연구실', NULL, '소비자 행동, 소비자의 확증편향적 정보처리, 광고 및 제품디자인의 시각효과, 기술 기반 광고에 대한 소비자 인식'),
    (170, '경영경제대학', '경영학부', '이유진', 'ylee@sejong.ac.kr', '부교수', '이유진 교수님 연구실', NULL, '회계감사, 재무회계, 국제회계'),
    (171, '경영경제대학', '경영학부', '한승오', 'sohan@sejong.ac.kr', '부교수', '한승오 교수님 연구실', NULL, '시장미시구조, 자산가격결정, 실증기업재무, 핀테크'),
    (172, '경영경제대학', '경영학부', '오재영', 'jyoh@sejong.ac.kr', '부교수', '오재영 교수님 연구실', NULL, 'AI·디지털 운영관리, 공급사슬 회복탄력성 및 지속가능성, 공급망 네트워크 및 기술혁신, 헬스케어 운영관리'),
    (173, '경영경제대학', '경영학부', '부찬일', 'chanil.boo@sejong.ac.kr', '조교수', '부찬일 교수님 연구실', NULL, '마케팅'),
    (174, '경영경제대학', '경영학부', '최철훈', 'chchoi@sejong.ac.kr', '조교수', '최철훈 교수님 연구실', NULL, '스마트 생산관리/공급사슬망관리, 지속가능한 생산관리/공급사슬망 관리, 재생에너지의 지속가능성'),
    (175, '경영경제대학', '경영학부', '황세준', 'sjhwang@sejong.ac.kr', '조교수', '황세준 교수님 연구실', NULL, NULL),
    (176, '경영경제대학', '경영학부', '김예원', 'yewonkim@sejong.ac.kr', '조교수', '김예원 교수님 연구실', 'https://prof.sejong.ac.kr/yewonkim/', '재무회계, 회계감사, 자본시장, 기업투자'),
    (177, '경영경제대학', '경영학부', 'Silver Chung', 'sichung@sejong.ac.kr', '조교수', 'Silver Chung 교수님 연구실', NULL, '기업 공시의 결정 요인과 결과; 경영자의 유인과 전략적 공시 행태; 그리고 감사 및 내부통제가 공시 신뢰성에 미치는 역할.'),
    (178, '경영경제대학', '경영학부', '이은미', 'tatum@sejong.ac.kr', '조교수', '이은미 교수님 연구실', 'https://prof.sejong.ac.kr/tatum/index.do', '국제경영 (Chinese MNE, Re-entry), 국제금융 (Corporate Finance, Digital Finance), ESG, 혁신 (핀테크, AI, 녹색혁신)'),
    (179, '경영경제대학', '경영학부', '석상익', 'seok@sejong.ac.kr', '조교수', '석상익 교수님 연구실', 'https://prof.sejong.ac.kr/seok', '자산가격결정, 행동재무, 투자자심리, ETF'),
    (180, '경영경제대학', '경영학부', 'CHAE MYOUNG JIN', 'mchae@sejong.ac.kr', '조교수', 'CHAE MYOUNG JIN 교수님 연구실', 'https://sites.google.com/view/mchae/home', '디지털마케팅, AI 및 기술 기반 마케팅, 기업의 사회적 책임, 지속가능한 소비, 헬스 마케팅'),
    (181, '경영경제대학', '경영학부', 'Kyungin Ryu', 'kryu@sejong.ac.kr', '조교수', 'Kyungin Ryu 교수님 연구실', 'https://sites.google.com/view/kyungin-ryu/about', '브랜딩, 스토리텔링, 브랜드 커뮤니티, 소비자 실존적 니즈'),
    (182, '경영경제대학', '경영학부', '김대종', 'daejong68@sejong.ac.kr', '조교수', '김대종 교수님 연구실', NULL, '무역 외환 국제금융 국제경제'),
    (183, '경영경제대학', '경영학부', '이성훈', 'fchub@sejong.ac.kr', '조교수', '이성훈 교수님 연구실', NULL, '- 프랜차이즈 - 마케팅'),
    (184, '경영경제대학', '경영학부', '이수준', 'soojunlee@sejong.ac.kr', '조교수', '이수준 교수님 연구실', NULL, '- 빅데이터 &AI - 머신러닝 - 이익의 질 이익조정 - 포트폴리오 매니지먼트'),
    (185, '경영경제대학', '경영학부', '오혜미', 'hyemioh@sejong.ac.kr', '조교수', '오혜미 교수님 연구실', NULL, '기업가정신, 창업 창업교육 창업생태계'),
    (186, '경영경제대학', '경영학부', '전민경', 'mgjeon@sejong.ac.kr', '조교수', '전민경 교수님 연구실', 'https://prof.sejong.ac.kr/mgjeon', '국제경영 및 매니지먼트, 기술경영, 혁신 및 전략경영, 지식경영, 휴먼-AI 교류'),
    (187, '경영경제대학', '경영학부', 'YIN MEILING', 'mlyin88@sejong.ac.kr', '조교수', 'YIN MEILING 교수님 연구실', 'https://prof.sejong.ac.kr/mlyin88', '디지털 마케팅, 소비자 행동, 뉴로마케팅'),
    (188, '경영경제대학', '경영학부', '양재장', 'doublej@sejong.ac.kr', '조교수', '양재장 교수님 연구실', 'https://prof.sejong.ac.kr/doublej', 'ESG, 지속가능경영, CSR, 환경 마케팅, 마케팅, 소비자행동'),
    (189, '경영경제대학', '경영학부', '김기현', 'kihyon@sejong.ac.kr', '조교수', '김기현 교수님 연구실', 'https://prof.sejong.ac.kr/kihyon/', '1 사회운동, 집합행동, 희망 2 CSR, ESG, 위선 3 덕윤리 4 인간중심 인공지능'),
    (190, '경영경제대학', '경제학과', '김정숙', 'js_kim@sejong.ac.kr', '부교수', '김정숙 교수님 연구실', 'https://sites.google.com/view/jungsukkim', '경제통합, 국제통상, 생산성'),
    (191, '경영경제대학', '경제학과', '이종은', 'ljongeun@sejong.ac.kr', '교수', '이종은 교수님 연구실', 'https://sites.google.com/view/jong-eun-lee/', '거시경제학, 지정학, 국제무역, 국제금융, 빅데이터 분석'),
    (192, '경영경제대학', '경제학과', '조원경', 'ableman@sejong.ac.kr', '교수', '조원경 교수님 연구실', NULL, '스테이블 코인의 시스템 리스크에 관한 소고'),
    (193, '경영경제대학', '경제학과', '김성은', 'seongeun.kim@sejong.ac.kr', '부교수', '김성은 교수님 연구실', 'https://sites.google.com/site/sekimphd', '거시경제학, 국제거시경제, 거시금융, 가족거시경제학'),
    (194, '경영경제대학', '경제학과', '이태환', 'thrhee@sejong.ac.kr', '부교수', '이태환 교수님 연구실', 'https://prof.sejong.ac.kr/thrhee', '거시경제, 조세재정, 국제경제'),
    (195, '경영경제대학', '경제학과', '이화령', 'hwaryung.lee@sejong.ac.kr', '부교수', '이화령 교수님 연구실', 'https://sites.google.com/site/hwaryunglee', '산업조직론, 반독점경제학, 응용미시'),
    (196, '경영경제대학', '경제학과', '최홍석', 'aitchchoi@sejong.ac.kr', '부교수', '최홍석 교수님 연구실', 'https://sites.google.com/view/aitchchoi', '금융경제학(자산가격결정이론, 투자론)'),
    (197, '경영경제대학', '경제학과', '오지윤', 'jiyoonoh@sejong.ac.kr', '부교수', '오지윤 교수님 연구실', NULL, '거시경제, 기업동학, 주택시장'),
    (198, '경영경제대학', '경제학과', '허영수', 'yheo@sejong.ac.kr', '조교수', '허영수 교수님 연구실', 'https://sites.google.com/view/yheo', '미시경제, 선택이론'),
    (199, '경영경제대학', '경제학과', '이승철', 'sclee@sejong.ac.kr', '조교수', '이승철 교수님 연구실', 'https://lofie21.github.io/', '거시경제학, 통화정책, 이질적 경제주체 모형, 통화정책 파급경로, 금융마찰, 소비 불평등, 탐색마찰, 개방경제 거시경제학, 경기변동론'),
    (200, '경영경제대학', '경제학과', 'ZHANG MENGZE', 'zhangmengze@sejong.ac.kr', '부교수', 'ZHANG MENGZE 교수님 연구실', 'https://prof.sejong.ac.kr/zhangmengze', '물류 경제, 중국 경제 발전, 소비자 행동'),
    (201, '경영경제대학', '경제학과', '최희영', 'hychoi@sejong.ac.kr', '조교수', '최희영 교수님 연구실', NULL, '보건,환경,응용미시'),
    (202, '경영경제대학', '경제학과', '이성아', 'sungahl@sejong.ac.kr', '초빙교수', '이성아 교수님 연구실', NULL, '국제무역, 경제발전, 거시경제'),
    (203, '경영경제대학', '경제학과', '장재철', 'jaechul@sejong.ac.kr', '초빙교수', '장재철 교수님 연구실', NULL, '국제경제학, 거시경제학, 화폐금융론, 자산관리경제학, 금융시장론'),
    (204, '경영경제대학', '경제학과', 'ZHANG YIZHOU', 'yizhou.zhang@sejong.ac.kr', '초빙교수', 'ZHANG YIZHOU 교수님 연구실', 'https://prof.sejong.ac.kr/yizhou_zhang', '문화산업, 응용미시'),
    (205, '인문과학대학', '국어국문학과', '김승구', 'modace@sejong.edu', '교수', '김승구 교수님 연구실', NULL, '한국현대문학, 일제강점기 문화사'),
    (206, '인문과학대학', '국어국문학과', '심지영', 'simji89@sejong.ac.kr', '부교수', '심지영 교수님 연구실', NULL, '한국어교육학, 국어학 (문법론), 대조언어학 (한중 대조분석), 외국어로서의한국어번역 (KFLT)'),
    (207, '인문과학대학', '국어국문학과', '이진', 'sumomo2025@sejong.ac.kr', '조교수', '이진 교수님 연구실', NULL, '한국어교육학, 말뭉치언어학'),
    (208, '인문과학대학', '국어국문학과', '장현묵', 'kaimuk@sejong.ac.kr', '초빙교수', '장현묵 교수님 연구실', NULL, '한국어교육, 한국어 읽기, 다문화교육'),
    (209, '인문과학대학', '영어데이터융합전공', '탁진영', 'jytak@sejong.ac.kr', '교수', '탁진영 교수님 연구실', 'https://sejong.elsevierpure.com/en/persons/jin-young-tak/', '언어학(음운론, 형태론), 아프리카어, 언어데이터 분석'),
    (210, '인문과학대학', '영어데이터융합전공', '곽은주', 'ejkwak@sejong.ac.kr', '교수', '곽은주 교수님 연구실', NULL, '의미론, 화용론, 번역학, 인공지능언어, 인지과학'),
    (211, '인문과학대학', '영어데이터융합전공', '김수연', 'kimsy@sejong.ac.kr', '교수', '김수연 교수님 연구실', 'https://prof.sejong.ac.kr/kimsy', '언어학, 언어모델연구, 빅데이터분석, 통사, 언어습득, 언어교육, 담화인지, 인지과학, 언어처리, 코퍼스 분석'),
    (212, '인문과학대학', '영어데이터융합전공', '이경랑', 'kranglee@sejong.ac.kr', '교수', '이경랑 교수님 연구실', 'https://prof.sejong.ac.kr/kranglee', '영어교육, 영어학습전략, 자기주도학습'),
    (213, '인문과학대학', '영어데이터융합전공', 'Shin Hye Won', 'hwshin@sejong.ac.kr', '부교수', 'Shin Hye Won 교수님 연구실', 'https://prof.sejong.ac.kr/hwshin', '인공지능 기반 교육, 언어습득, 언어평가'),
    (214, '인문과학대학', '영어데이터융합전공', '김원빈', 'wbkim@sejong.ac.kr', '조교수', '김원빈 교수님 연구실', NULL, '코퍼스언어학, 인공지능, 자연어처리'),
    (215, '인문과학대학', '영어데이터융합전공', '정영희', 'chungyh@sejong.ac.kr', '명예교수', '정영희 교수님 연구실', NULL, NULL),
    (216, '인문과학대학', '영어데이터융합전공', '이동영', 'dylee7@sejong.ac.kr', '명예교수', '이동영 교수님 연구실', NULL, '전산언어학, 기계번역, 자료기반 언어처리'),
    (217, '인문과학대학', '국제일본학전공', '이병진', 'yes1121@sejong.ac.kr', '교수', '이병진 교수님 연구실', NULL, '초역문화과학/비교문학비교문화/국제일본학(일본사회, 문화론)/야나기 무네요시(柳宗悅),아사카와 다쿠미(淺川巧)의 공예론'),
    (218, '인문과학대학', '국제일본학전공', '김도형', 'artenet@sejong.ac.kr', '조교수', '김도형 교수님 연구실', NULL, '일본근대사 / 일본사상사 / 동아시아사상사'),
    (219, '인문과학대학', '국제일본학전공', '김효숙', 'hsk@sejong.ac.kr', '조교수', '김효숙 교수님 연구실', NULL, '일본고전문학 동아시아비교문학 일본문화의 수용과 변용'),
    (220, '인문과학대학', '국제일본학전공', '이승준', 'leesj7137@sejong.ac.kr', '조교수', '이승준 교수님 연구실', 'https://prof.sejong.ac.kr/leesj7137/', '일본근현대문학·문화, 전후 대중문화와 신체표상, 일본 포스트모더니즘'),
    (221, '인문과학대학', '중국통상학전공', '최필수', 'ccppss@sejong.ac.kr', '교수', '최필수 교수님 연구실', NULL, '중국경제, 한중관계'),
    (222, '인문과학대학', '중국통상학전공', '강필임', 'pilyim@sejong.ac.kr', '교수', '강필임 교수님 연구실', 'https://home.sejong.ac.kr/~pilyim/', '한중문화비교, 한류, 중국문학. 중국시, 위진남북조시, 당시.'),
    (223, '인문과학대학', '중국통상학전공', '이문기', 'okmklee@sejong.ac.kr', '교수', '이문기 교수님 연구실', NULL, '중국정치, 한중관계'),
    (224, '인문과학대학', '중국통상학전공', '노성호', 'sunghorho@sejong.ac.kr', '교수', '노성호 교수님 연구실', NULL, '개발경제학, 혁신연구, 기업가정신, 중국경제'),
    (225, '인문과학대학', '중국통상학전공', 'HE YUGANG', '1293647581@sejong.ac.kr', '조교수', 'HE YUGANG 교수님 연구실', 'https://prof.sejong.ac.kr/1293647581/index.do', '국제 경제, 국제무역, 에너지경제, 환경경제'),
    (226, '인문과학대학', '중국통상학전공', 'BAI GUIHUA', 'baiguihua@naver.com', '초빙교수', 'BAI GUIHUA 교수님 연구실', NULL, '정책과정, 사회정책, 중국의 중앙-지방 관계, 중국의 정책제정과정'),
    (227, '인문과학대학', '역사학과', '이지은', 'jieunlee333@sejong.ac.kr', '부교수', '이지은 교수님 연구실', NULL, NULL),
    (228, '인문과학대학', '역사학과', '우은진', 'redqin@sejong.ac.kr', '부교수', '우은진 교수님 연구실', 'https://prof.sejong.ac.kr/redqin', '인골고고학, 사람뼈대학, 생물인류학'),
    (229, '인문과학대학', '역사학과', '박선영', 'syp@sejong.ac.kr', '부교수', '박선영 교수님 연구실', NULL, '동아시아근현대사'),
    (230, '인문과학대학', '역사학과', '정연철', 'yeuncheoljeong@sejong.ac.kr', '조교수', '정연철 교수님 연구실', NULL, '천체물리 분광학 항성 천체물리학 양자역학의 역사와 철학 현대우주론의 역사와 철학'),
    (231, '인문과학대학', '교육학과', '권현수', 'hskwon@sejong.ac.kr', '교수', '권현수 교수님 연구실', 'https://prof.sejong.ac.kr/hskwon', '통합교육, 교사교육, 특수아상담, 부모상담, 학습상담'),
    (232, '인문과학대학', '교육학과', '김희연', 'hykim@sejong.ac.kr', '교수', '김희연 교수님 연구실', NULL, '교육과정, 질적연구방법, 유아교육'),
    (233, '인문과학대학', '교육학과', '민경석', 'minkyungseok@sejong.ac.kr', '교수', '민경석 교수님 연구실', NULL, '문항반응이론, 대규모 학생평가, AI 기반 적응형 검사, 인과추론'),
    (234, '인문과학대학', '교육학과', '이수정', 'soojlee@sejong.ac.kr', '부교수', '이수정 교수님 연구실', NULL, '교육행정, 고등교육'),
    (235, '인문과학대학', '교육학과', '정은주', 'doduli@sejong.ac.kr', '부교수', '정은주 교수님 연구실', 'https://home.sejong.ac.kr/~doduli/', '교육심리학, 교육측정 및 평가, 진로상담'),
    (236, '인문과학대학', '교육학과', 'JIN YUANYING', 'yyjin@sejong.ac.kr', '조교수', 'JIN YUANYING 교수님 연구실', 'https://home.sejong.ac.kr/~yyjin/', '학업적응, 상담에 대한 태도, 다문화 상담'),
    (237, '사회과학대학', '행정학과', '김미정', 'meejungk@sejong.ac.kr', '조교수', '김미정 교수님 연구실', 'https://prof.sejong.ac.kr/meejungk', '실증 정책 분석 및 평가, 응용 미시경제학, 기업 및 기업가 활동 분석'),
    (238, '사회과학대학', '행정학과', '이수연', 'suyunlee@sejong.ac.kr', '교수', '이수연 교수님 연구실', 'https://home.sejong.ac.kr/~suyunlee/', 'AI와 노인 커뮤니티케어정책, 헬스케어정책, 복지정책, 다문화·이민정책'),
    (239, '사회과학대학', '행정학과', '변창흠', 'changbyeon@sejong.ac.kr', '교수', '변창흠 교수님 연구실', 'https://home.sejong.ac.kr/~changbyeon/', '도시행정, 부동산정책, 지방행정, 주택정책, 도시재생, 지역발전, 실행모델, 토지정책'),
    (240, '사회과학대학', '행정학과', '이창길', 'cklee@sejong.ac.kr', '교수', '이창길 교수님 연구실', 'https://home.sejong.ac.kr/~cklee/', '조직이론, 인사행정, 행정개혁, 영화조직, 국제개발'),
    (241, '사회과학대학', '행정학과', '곽창규', 'ckwak@sejong.ac.kr', '부교수', '곽창규 교수님 연구실', NULL, '정책네트워크, 규제정책, 과학기술정책'),
    (242, '사회과학대학', '행정학과', '신정은', 'jeongeunshin12@sejong.ac.kr', '부교수', '신정은 교수님 연구실', NULL, '온라인 플랫폼 관련 공정거래 및 노동시장의 법과 제도, 국제 무역'),
    (243, '사회과학대학', '행정학과', '최안나', 'anna.choi@sejong.ac.kr', '부교수', '최안나 교수님 연구실', 'https://prof.sejong.ac.kr/anna_choi', '정책 분석 및 평가, 응용 미시 경제학 (보건 경제학), 보건 정책'),
    (244, '사회과학대학', '행정학과', '박혜윤', 'hypark911@gmail.com', '초빙교수', '박혜윤 교수님 연구실', NULL, NULL),
    (245, '사회과학대학', '미디어커뮤니케이션학과', '천정원', 'jwchun@sejong.ac.kr', '조교수', '천정원 교수님 연구실', 'https://prof.sejong.ac.kr/jwchun/index.do', '디지털 PR 전략, AI 기반 전략 커뮤니케이션, 뉴테크놀로지 기반 친사회적 행동 촉진'),
    (246, '사회과학대학', '미디어커뮤니케이션학과', '신은자', 'ejshin@sejong.ac.kr', '교수', '신은자 교수님 연구실', NULL, '정보학 정보공유 학술 출판 학술 커뮤니케이션'),
    (247, '사회과학대학', '미디어커뮤니케이션학과', '손승혜', 'shsohn@sejong.ac.kr', '교수', '손승혜 교수님 연구실', NULL, '뉴미디어 수용자 & 정책'),
    (248, '사회과학대학', '미디어커뮤니케이션학과', '이귀옥', 'guiohk@sejong.ac.kr', '교수', '이귀옥 교수님 연구실', 'https://home.sejong.ac.kr/~guiohk/', '광고메시지 전략, 헬스커뮤니케이션, 광고와 젠더이슈, 미디어콘텐츠 소비'),
    (249, '사회과학대학', '미디어커뮤니케이션학과', '오정호', 'jhooh@sejong.ac.kr', '교수', '오정호 교수님 연구실', NULL, '매체경제학, 조사방법론, 미디어정책'),
    (250, '사회과학대학', '미디어커뮤니케이션학과', '임종수', 'jslim123@sejong.ac.kr', '교수', '임종수 교수님 연구실', 'https://prof.sejong.ac.kr/jslim123/index.do', '문화연구, 스트리밍 미디어, OTT'),
    (251, '사회과학대학', '미디어커뮤니케이션학과', '박가인', 'park@sejong.ac.kr', '부교수', '박가인 교수님 연구실', 'https://prof.sejong.ac.kr/park', '디지털미디어, AI 커뮤니케이션'),
    (252, '사회과학대학', '미디어커뮤니케이션학과', '송용휘', 'gregsong@sejong.ac.kr', '조교수', '송용휘 교수님 연구실', 'https://prof.sejong.ac.kr/gregsong/', 'AI 기반 광고, 소셜미디어, 소비자 심리'),
    (253, '사회과학대학', '미디어커뮤니케이션학과', '김미희', 'mhkim2008@sejong.ac.kr', '부교수', '김미희 교수님 연구실', NULL, '디지털/AI 기반 저널리즘, 뉴스 큐레이션, 미디어 테크놀로지'),
    (254, '사회과학대학', '미디어커뮤니케이션학과', '김학신', 'hark0802@sejong.ac.kr', '초빙교수', '김학신 교수님 연구실', NULL, ' 미디어 테크놀로지와 인지 과정 연구 (Eye-Tracking, VR, AR, HCI 커뮤니케이션) - AI 에이전트 기반 디지털 미디어 광고 전략 - 디지털 OOH 효과 측정 모델 개발 - 넷플릭스 스토리텔링·소셜 캠페인 통합 분석'),
    (255, '사회과학대학', '법학과', '최승재', 'sjchoi@sejong.ac.kr', '교수', '최승재 교수님 연구실', NULL, NULL),
    (256, '사회과학대학', '법학과', '이준호', 'leejoonho63@sejong.ac.kr', '교수', '이준호 교수님 연구실', 'https://home.sejong.ac.kr/~openmajor/', '민사법'),
    (257, '인공지능융합대학', '디자인이노베이션전공', '전환수', 'designexp@sejong.ac.kr', '조교수', '전환수 교수님 연구실', 'https://home.sejong.ac.kr/~designexp', '산업디자인, 제품디자인, CMF디자인, 디자인엔지니어링, AI디자인, Physical UX 디자인'),
    (258, '인공지능융합대학', '디자인이노베이션전공', '박용진', 'yjpark@sejong.ac.kr', '교수', '박용진 교수님 연구실', NULL, '모션그래픽디자인, Brand in Motion 디지털미디어디자인 인포메이션디자인 타이포그래피'),
    (259, '인공지능융합대학', '디자인이노베이션전공', '김진성', 'jinsungk@sejong.ac.kr', '부교수', '김진성 교수님 연구실', NULL, '제품 / 모빌리티 디자인 및 UX / PUI'),
    (260, '인공지능융합대학', '디자인이노베이션전공', '민자경', 'mjk@sejong.ac.kr', '부교수', '민자경 교수님 연구실', NULL, 'BX Design, Service Design, UI&UX Design, AI&XR Design'),
    (261, '인공지능융합대학', '디자인이노베이션전공', '김영은', 'youngkim@sejong.ac.kr', '조교수', '김영은 교수님 연구실', NULL, '인터랙션디자인 (HCID), UX 디자인, 시각디자인'),
    (262, '인공지능융합대학', '만화애니메이션텍전공', '이순기', 'skllsk@sejong.ac.kr', '조교수', '이순기 교수님 연구실', NULL, '만화&웹툰'),
    (263, '인공지능융합대학', '만화애니메이션텍전공', '김세훈', 'kimsh@sejong.ac.kr', '교수', '김세훈 교수님 연구실', NULL, '애니메이션, 웹툰, 영화, VFX'),
    (264, '인공지능융합대학', '만화애니메이션텍전공', '한창완', 'htank@sejong.ac.kr', '교수', '한창완 교수님 연구실', NULL, '만화산업, 애니메이션산업, 캐릭터 비즈니스, 게임산업 등의 관련이론, 시장분석, 마케팅, 기획, 정책연구'),
    (265, '인공지능융합대학', '만화애니메이션텍전공', '강윤극', 'ykang@sejong.ac.kr', '교수', '강윤극 교수님 연구실', 'https://home.sejong.ac.kr/~cguniv/', 'Gen AI, Animation, Visual Effects(VFX), XR, AR, Game, Hologram, Immersive Content, ICVFX, 버츄얼휴먼 등 Computer Graphics 관련분야 연구. 과학기술정통부 국방분야 실감콘텐츠랩 수행중.'),
    (266, '인공지능융합대학', '만화애니메이션텍전공', '박재우', 'jaewoopark@sejong.ac.kr', '부교수', '박재우 교수님 연구실', 'https://prof.sejong.ac.kr/jaewoopark', '애니메이션: AI 애니메이션 연출, 기획, 시나리오, 프로듀싱, 파이프라인 설계 버추얼콘텐츠: 버추얼 프로덕션, 버추얼 확장 콘텐츠, 버추얼 휴먼, 버추얼 아이돌'),
    (267, '인공지능융합대학', '만화애니메이션텍전공', '최서영', 'seolux@sejong.ac.kr', '조교수', '최서영 교수님 연구실', NULL, '생성형 AI 영상콘텐츠, AI 이미징, 버추얼 콘텐츠, 2D/3D 영상디자인, 모션그래픽, 애니메이션, 미디어 아트 및 전시 콘텐츠'),
    (268, '인공지능융합대학', '만화애니메이션텍전공', '김영미', 'imzerobeauty@sejong.ac.kr', '부교수', '김영미 교수님 연구실', NULL, NULL),
    (269, '인공지능융합대학', '만화애니메이션텍전공', '김진영', 'jinuoung@sejong.ac.kr', '초빙교수', '김진영 교수님 연구실', NULL, '영상매체 연구 분석, 시나리오 창작, 이미지 비주얼 연구'),
    (270, '인공지능융합대학', '만화애니메이션텍전공', '한동훈', 'bro3150@naver.com', '초빙교수', '한동훈 교수님 연구실', NULL, NULL),
    (271, '인공지능융합대학', '만화애니메이션텍전공', '이상구', 'papabingo@sejong.ac.kr', '초빙교수', '이상구 교수님 연구실', NULL, NULL),
    (272, '인공지능융합대학', '만화애니메이션텍전공', '하선영', 'sssyyyyy00@naver.com', '초빙교수', '하선영 교수님 연구실', NULL, '웹툰'),
    (273, '호텔관광대학', '호텔관광경영학전공', '연지환', 'jhyeon@sejong.ac.kr', '부교수', '연지환 교수님 연구실', 'http://home.sejong.ac.kr/~jhyeon/', 'CSR, ESG, 기업재무분석, 정책분석, 공유경제'),
    (274, '호텔관광대학', '호텔관광경영학전공', '조용현', 'ycho@sejong.ac.kr', '교수', '조용현 교수님 연구실', NULL, NULL),
    (275, '호텔관광대학', '호텔관광경영학전공', '조미혜', 'mihec@sejong.ac.kr', '교수', '조미혜 교수님 연구실', NULL, '관광마케팅, 관광정보/홍보, 소비자행동, 온라인/모바일 마케팅, 문화관광콘텐츠 등'),
    (276, '호텔관광대학', '호텔관광경영학전공', '김형곤', 'hkim@sejong.ac.kr', '교수', '김형곤 교수님 연구실', NULL, '관광행동, 문화관광, 축제경영'),
    (277, '호텔관광대학', '호텔관광경영학전공', '안윤영', 'koala@sejong.ac.kr', '교수', '안윤영 교수님 연구실', 'https://prof.sejong.ac.kr/koala', '기업가치평가, 무형자산, 재무분석가, 정보비대칭, 환대산업 경영이슈'),
    (278, '호텔관광대학', '호텔관광경영학전공', '이충훈', 'chleee@sejong.ac.kr', '교수', '이충훈 교수님 연구실', 'https://prof.sejong.ac.kr/chleee', '포용적·지속가능한 관광혁신, 소비자 후생, 실험연구'),
    (279, '호텔관광대학', '호텔관광경영학전공', '한희섭', 'heesup@sejong.ac.kr', '교수', '한희섭 교수님 연구실', 'http://home.sejong.ac.kr/~heesup/', 'AI관광, ESG, 서비스혁신, 관광지개발, 조직행동, 서비스로봇, 환대산업마케팅'),
    (280, '호텔관광대학', '호텔관광경영학전공', '이슬기', 'seulkilee@sejong.ac.kr', '교수', '이슬기 교수님 연구실', 'https://prof.sejong.ac.kr/seulkilee', '공간계량경제모형, 자산관리, 수익관리'),
    (281, '호텔관광대학', '호텔관광경영학전공', '고영대', 'youngdae.ko@sejong.ac.kr', '교수', '고영대 교수님 연구실', NULL, '데이터/비즈니스 애널리틱스, 시스템 최적화, 인공지능/알고리즘, 피지컬AI'),
    (282, '호텔관광대학', '호텔관광경영학전공', '김진후', 'jinhookim@sejong.ac.kr', '부교수', '김진후 교수님 연구실', NULL, '국제 관광, 관광 자료 분석, 호텔·관광 기업 재무적 분석'),
    (283, '호텔관광대학', '호텔관광경영학전공', '변재문', 'jaemun.byun@sejong.ac.kr', '부교수', '변재문 교수님 연구실', 'https://prof.sejong.ac.kr/jaemun_byun', '관광지 마케팅, 관광정책/전략, 관광객 행동, MICE/축제'),
    (284, '호텔관광대학', '호텔관광경영학전공', '최충범', 'cbchoi@sejong.ac.kr', '부교수', '최충범 교수님 연구실', 'https://prof.sejong.ac.kr/cbchoi', '서비스마케팅, 소비자행동, 수익관리, 가격전략'),
    (285, '호텔관광대학', '호텔관광경영학전공', '안영주', 'yjahn@sejong.ac.kr', '부교수', '안영주 교수님 연구실', NULL, '마케팅, 관광지 경영, 소비자행동 (Marketing, Destination Management, Consumer Behavior)'),
    (286, '호텔관광대학', '호텔관광경영학전공', 'Seweryn ZIELINSKI', 'zielinski@sejong.ac.kr', '부교수', 'Seweryn ZIELINSKI 교수님 연구실', 'https://sejong.elsevierpure.com/en/persons/zielinski-seweryn/', 'Sustainable Tourism, Planning and Development, Cultural Tourism, Community-based Tourism, Ecotourism, Nature-based Tourism, Beach Tourism and Beach Management, Tourism Eco-labels'),
    (287, '호텔관광대학', '호텔관광경영학전공', 'Eck Thomas Christopher', 'teck@sejong.ac.kr', '조교수', 'Eck Thomas Christopher 교수님 연구실', NULL, '체험관광, 유적지관광'),
    (288, '호텔관광대학', '호텔관광경영학전공', '김민지', 'kmj@sejong.ac.kr', '조교수', '김민지 교수님 연구실', NULL, '디지털마케팅, 메시지 프레이밍, 소비자 의사결정'),
    (289, '호텔관광대학', '호텔관광경영학전공', 'SARKAR MITALI', 'mitali@sejong.ac.kr', '조교수', 'SARKAR MITALI 교수님 연구실', 'http://prof.sejong.ac.kr/mitali', '호텔 및 관광 공급망, 관광물류, 폐기물 관리'),
    (290, '호텔관광대학', '호텔관광경영학전공', 'MARKHAM-KIM HEATHER MARIE', 'hmk@sejong.ac.kr', '조교수', 'MARKHAM-KIM HEATHER MARIE 교수님 연구실', NULL, NULL),
    (291, '호텔관광대학', '호텔관광경영학전공', 'Jiaolong Cheng', 'jc01780@sejong.ac.kr', '초빙교수', 'Jiaolong Cheng 교수님 연구실', NULL, 'Applications and Implications of Digital Technology, Customer Behaviour, Customer Psychology'),
    (292, '호텔관광대학', '호텔관광경영학전공', '김홍범', NULL, '명예교수', '김홍범 교수님 연구실', NULL, '조사방법, 마케팅조사, 정보시스템'),
    (293, '호텔관광대학', '호텔관광경영학전공', '임은순', NULL, '명예교수', '임은순 교수님 연구실', NULL, '관광경제'),
    (294, '호텔관광대학', '호텔관광경영학전공', '이형룡', 'hrlee@sejong.ac.kr', '명예교수', '이형룡 교수님 연구실', NULL, '환대산업 인적자원관리, 조직행동, 소비자 행동'),
    (295, '호텔관광대학', '외식경영학전공', '이승주', 'sejlee@sejong.ac.kr', '교수', '이승주 교수님 연구실', 'https://prof.sejong.ac.kr/sejlee/index.do', '1) 식품의 정량적 감각특성 분석 및 소비자 기호도 조사 연구 2) 감각특성, 소비자 기호도 및 기기분석 결과를 바탕으로 한 표준화 연구 : 다양한 다변량 분석(PCA, PLSR, 인공신경망, Fuzzy 등) 적용 3) 고령자를 위한 텍스쳐 변형 식품관련 감각특성 분석 및 임상조사 4) 한국 전통식품관련 제품개발 연구'),
    (296, '호텔관광대학', '외식경영학전공', '정유경', 'ykchong@sejong.ac.kr', '교수', '정유경 교수님 연구실', NULL, '- 호텔외식경영 및 마케팅 - Hospitality CRM 및 데이터베이스마케팅 - 외식 프랜차이즈 경영'),
    (297, '호텔관광대학', '외식경영학전공', '유승석', 'yss2@sejong.ac.kr', '교수', '유승석 교수님 연구실', NULL, '식품조리과학, 식품가공 및 분석'),
    (298, '호텔관광대학', '외식경영학전공', '정장호', 'cchung@sejong.ac.kr', '교수', '정장호 교수님 연구실', 'https://home.sejong.ac.kr/~cchung/', '발효미생물, 발효식품, 조리과학'),
    (299, '호텔관광대학', '외식경영학전공', '박광민', 'kmpark@sejong.ac.kr', '교수', '박광민 교수님 연구실', 'https://prof.sejong.ac.kr/kmpark', '머신러닝과 AI를 활용한 빅데이터 분석 외식전략경영 외식 재무 및 회계 행동경제학 기반 의사결정'),
    (300, '호텔관광대학', '외식경영학전공', '류기상', 'kryu11@sejong.ac.kr', '교수', '류기상 교수님 연구실', NULL, 'Foodservice Management Hospitality & Tourism Marketing Restaurant Service Quality Customer Satisfaction'),
    (301, '호텔관광대학', '외식경영학전공', '황진수', 'jhwang@sejong.ac.kr', '교수', '황진수 교수님 연구실', 'https://home.sejong.ac.kr/~jhwang/', '기술기반 서비스'),
    (302, '호텔관광대학', '조리서비스경영학과', '함동철', 'fsc77@sejong.ac.kr', '초빙교수', '함동철 교수님 연구실', NULL, '외식창업경영'),
    (303, '호텔관광대학', '호텔외식관광프랜차이즈경영학과', '송병화', 'arhensbh@sejong.ac.kr', '초빙교수', '송병화 교수님 연구실', NULL, '프랜차이즈 비즈니스');

-- Include the existing primary department of three cross-college professors.
INSERT INTO v44_catalog_affiliation (record_key, college_name, department_name, position)
VALUES
    (4, '공과대학', '건축공학과', '부교수'),
    (5, '공과대학', '건축공학과', '교수'),
    (6, '공과대학', '건축공학과', '교수'),
    (7, '공과대학', '건축공학과', '교수'),
    (8, '공과대학', '건축공학과', '교수'),
    (9, '공과대학', '건축공학과', '교수'),
    (10, '공과대학', '건축공학과', '교수'),
    (11, '공과대학', '건축공학과', '교수'),
    (12, '공과대학', '건축공학과', '부교수'),
    (13, '공과대학', '건축공학과', '조교수'),
    (14, '공과대학', '건축공학과', '부교수'),
    (15, '공과대학', '건축학과', '교수'),
    (16, '공과대학', '건축학과', '교수'),
    (17, '공과대학', '건축학과', '교수'),
    (18, '공과대학', '건축학과', '교수'),
    (19, '공과대학', '건축학과', '교수'),
    (20, '공과대학', '건축학과', '조교수'),
    (21, '공과대학', '건설환경공학과', '조교수'),
    (22, '공과대학', '건설환경공학과', '교수'),
    (23, '공과대학', '건설환경공학과', '교수'),
    (24, '공과대학', '건설환경공학과', '교수'),
    (25, '공과대학', '건설환경공학과', '교수'),
    (26, '공과대학', '건설환경공학과', '교수'),
    (27, '공과대학', '건설환경공학과', '교수'),
    (28, '공과대학', '건설환경공학과', '부교수'),
    (29, '공과대학', '건설환경공학과', '조교수'),
    (30, '공과대학', '건설환경공학과', '조교수'),
    (31, '공과대학', '건설환경공학과', '조교수'),
    (32, '공과대학', '건설환경공학과', '부교수'),
    (33, '공과대학', '건설환경공학과', '조교수'),
    (34, '공과대학', '건설환경공학과', '석좌교수'),
    (35, '공과대학', '환경융합공학과', '부교수'),
    (36, '공과대학', '환경융합공학과', '교수'),
    (37, '공과대학', '환경융합공학과', '교수'),
    (38, '공과대학', '환경융합공학과', '교수'),
    (39, '공과대학', '환경융합공학과', '교수'),
    (40, '공과대학', '환경융합공학과', '부교수'),
    (41, '공과대학', '환경융합공학과', '조교수'),
    (42, '공과대학', '환경융합공학과', '부교수'),
    (43, '공과대학', '환경융합공학과', '조교수'),
    (44, '공과대학', '환경융합공학과', '조교수'),
    (45, '공과대학', '에너지자원공학과', '교수'),
    (46, '공과대학', '에너지자원공학과', '교수'),
    (47, '공과대학', '에너지자원공학과', '교수'),
    (48, '공과대학', '에너지자원공학과', '교수'),
    (49, '공과대학', '에너지자원공학과', '교수'),
    (50, '공과대학', '에너지자원공학과', '교수'),
    (51, '공과대학', '에너지자원공학과', '교수'),
    (52, '공과대학', '에너지자원공학과', '교수'),
    (53, '공과대학', '에너지자원공학과', '교수'),
    (54, '공과대학', '에너지자원공학과', '부교수'),
    (55, '공과대학', '에너지자원공학과', '조교수'),
    (56, '공과대학', '기계공학과', '교수'),
    (57, '공과대학', '기계공학과', '교수'),
    (58, '공과대학', '기계공학과', '교수'),
    (59, '공과대학', '기계공학과', '교수'),
    (60, '공과대학', '기계공학과', '교수'),
    (61, '공과대학', '기계공학과', '교수'),
    (62, '공과대학', '기계공학과', '교수'),
    (63, '공과대학', '기계공학과', '교수'),
    (64, '공과대학', '기계공학과', '교수'),
    (65, '공과대학', '기계공학과', '조교수'),
    (66, '공과대학', '기계공학과', '부교수'),
    (67, '공과대학', '기계공학과', '조교수'),
    (68, '공과대학', '기계공학과', '조교수'),
    (69, '공과대학', '기계공학과', '조교수'),
    (70, '공과대학', '기계공학과', '조교수'),
    (71, '공과대학', '국방AI융합시스템공학과', '부교수'),
    (1, '공과대학', '국방AI융합시스템공학과', '교수'),
    (2, '공과대학', '국방AI융합시스템공학과', '교수'),
    (3, '공과대학', '국방AI융합시스템공학과', '교수'),
    (72, '공과대학', '국방AI융합시스템공학과', '교수'),
    (73, '공과대학', '국방AI융합시스템공학과', '교수'),
    (74, '공과대학', '국방AI융합시스템공학과', '교수'),
    (75, '공과대학', '국방AI융합시스템공학과', '부교수'),
    (76, '공과대학', '국방AI융합시스템공학과', '조교수'),
    (77, '공과대학', '국방AI융합시스템공학과', '조교수'),
    (78, '공과대학', '국방AI융합시스템공학과', '초빙교수'),
    (79, '공과대학', '국방AI융합시스템공학과', '초빙교수'),
    (80, '공과대학', '국방AI융합시스템공학과', '초빙교수'),
    (81, '공과대학', '국방AI융합시스템공학과', '석좌교수'),
    (82, '공과대학', '국방AI융합시스템공학과', '석좌교수'),
    (83, '공과대학', '나노신소재공학과', '교수'),
    (84, '공과대학', '나노신소재공학과', '교수'),
    (85, '공과대학', '나노신소재공학과', '교수'),
    (86, '공과대학', '나노신소재공학과', '교수'),
    (87, '공과대학', '나노신소재공학과', '교수'),
    (88, '공과대학', '나노신소재공학과', '교수'),
    (89, '공과대학', '나노신소재공학과', '교수'),
    (90, '공과대학', '나노신소재공학과', '교수'),
    (91, '공과대학', '나노신소재공학과', '교수'),
    (92, '공과대학', '나노신소재공학과', '교수'),
    (93, '공과대학', '나노신소재공학과', '교수'),
    (94, '공과대학', '나노신소재공학과', '교수'),
    (95, '공과대학', '나노신소재공학과', '교수'),
    (96, '공과대학', '나노신소재공학과', '교수'),
    (97, '공과대학', '나노신소재공학과', '교수'),
    (98, '공과대학', '나노신소재공학과', '부교수'),
    (99, '공과대학', '나노신소재공학과', '부교수'),
    (100, '공과대학', '나노신소재공학과', '부교수'),
    (101, '공과대학', '나노신소재공학과', '부교수'),
    (102, '공과대학', '나노신소재공학과', '부교수'),
    (103, '공과대학', '나노신소재공학과', '부교수'),
    (104, '공과대학', '나노신소재공학과', '부교수'),
    (105, '공과대학', '나노신소재공학과', '부교수'),
    (106, '공과대학', '나노신소재공학과', '조교수'),
    (107, '공과대학', '나노신소재공학과', '조교수'),
    (108, '공과대학', '나노신소재공학과', '조교수'),
    (109, '공과대학', '나노신소재공학과', '조교수'),
    (110, '공과대학', '나노신소재공학과', '조교수'),
    (111, '공과대학', '나노신소재공학과', '조교수'),
    (112, '공과대학', '나노신소재공학과', '조교수'),
    (113, '공과대학', '나노신소재공학과', '대우교수'),
    (114, '공과대학', '양자원자력공학과', '교수'),
    (115, '공과대학', '양자원자력공학과', '교수'),
    (116, '공과대학', '양자원자력공학과', '교수'),
    (117, '공과대학', '양자원자력공학과', '교수'),
    (118, '공과대학', '양자원자력공학과', '부교수'),
    (119, '공과대학', '양자원자력공학과', '부교수'),
    (120, '공과대학', '양자원자력공학과', '조교수'),
    (121, '공과대학', '양자원자력공학과', '조교수'),
    (122, '공과대학', '우주항공공학전공', '전임교원'),
    (123, '공과대학', '우주항공공학전공', '전임교원'),
    (124, '공과대학', '우주항공공학전공', '전임교원'),
    (125, '공과대학', '우주항공공학전공', '전임교원'),
    (126, '공과대학', '우주항공공학전공', '전임교원'),
    (127, '공과대학', '우주항공공학전공', '전임교원'),
    (128, '공과대학', '우주항공공학전공', '전임교원'),
    (129, '공과대학', '우주항공공학전공', '전임교원'),
    (130, '공과대학', '우주항공공학전공', '전임교원'),
    (131, '공과대학', '우주항공공학전공', '전임교원'),
    (132, '공과대학', '우주항공공학전공', '전임교원'),
    (133, '공과대학', '우주항공공학전공', '전임교원'),
    (134, '공과대학', '우주항공공학전공', '전임교원'),
    (135, '공과대학', '우주항공공학전공', '연구중점전임교원'),
    (136, '공과대학', '우주항공공학전공', '전임교원'),
    (122, '공과대학', '지능형드론융합전공', '전임교원'),
    (123, '공과대학', '지능형드론융합전공', '전임교원'),
    (124, '공과대학', '지능형드론융합전공', '전임교원'),
    (125, '공과대학', '지능형드론융합전공', '전임교원'),
    (126, '공과대학', '지능형드론융합전공', '전임교원'),
    (127, '공과대학', '지능형드론융합전공', '전임교원'),
    (130, '공과대학', '지능형드론융합전공', '전임교원'),
    (132, '공과대학', '지능형드론융합전공', '전임교원'),
    (133, '공과대학', '지능형드론융합전공', '전임교원'),
    (134, '공과대학', '지능형드론융합전공', '전임교원'),
    (137, '공과대학', '지능형드론융합전공', '전임교원'),
    (138, '공과대학', '지능형드론융합전공', '연구중점전임교원'),
    (139, '공과대학', '지능형드론융합전공', '연구중점전임교원'),
    (128, '공과대학', '항공시스템공학과', '전임교원'),
    (129, '공과대학', '항공시스템공학과', '전임교원'),
    (131, '공과대학', '항공시스템공학과', '전임교원'),
    (140, '공과대학', '항공시스템공학과', '연구중점전임교원'),
    (141, '공과대학', '항공시스템공학과', '비전임교원'),
    (142, '공과대학', '항공시스템공학과', '비전임교원'),
    (143, '공과대학', '항공시스템공학과', '비전임교원'),
    (144, '공과대학', '항공시스템공학과', '비전임교원'),
    (145, '공과대학', '항공시스템공학과', '산학협력중점교수'),
    (146, '경영경제대학', '경영학부', '교수'),
    (147, '경영경제대학', '경영학부', '교수'),
    (148, '경영경제대학', '경영학부', '교수'),
    (149, '경영경제대학', '경영학부', '교수'),
    (150, '경영경제대학', '경영학부', '교수'),
    (151, '경영경제대학', '경영학부', '교수'),
    (152, '경영경제대학', '경영학부', '교수'),
    (153, '경영경제대학', '경영학부', '교수'),
    (154, '경영경제대학', '경영학부', '교수'),
    (155, '경영경제대학', '경영학부', '교수'),
    (156, '경영경제대학', '경영학부', '교수'),
    (157, '경영경제대학', '경영학부', '교수'),
    (158, '경영경제대학', '경영학부', '교수'),
    (159, '경영경제대학', '경영학부', '교수'),
    (160, '경영경제대학', '경영학부', '교수'),
    (161, '경영경제대학', '경영학부', '부교수'),
    (162, '경영경제대학', '경영학부', '부교수'),
    (163, '경영경제대학', '경영학부', '부교수'),
    (164, '경영경제대학', '경영학부', '부교수'),
    (165, '경영경제대학', '경영학부', '부교수'),
    (166, '경영경제대학', '경영학부', '부교수'),
    (167, '경영경제대학', '경영학부', '부교수'),
    (168, '경영경제대학', '경영학부', '부교수'),
    (169, '경영경제대학', '경영학부', '부교수'),
    (170, '경영경제대학', '경영학부', '부교수'),
    (171, '경영경제대학', '경영학부', '부교수'),
    (172, '경영경제대학', '경영학부', '부교수'),
    (173, '경영경제대학', '경영학부', '조교수'),
    (174, '경영경제대학', '경영학부', '조교수'),
    (175, '경영경제대학', '경영학부', '조교수'),
    (176, '경영경제대학', '경영학부', '조교수'),
    (177, '경영경제대학', '경영학부', '조교수'),
    (178, '경영경제대학', '경영학부', '조교수'),
    (179, '경영경제대학', '경영학부', '조교수'),
    (180, '경영경제대학', '경영학부', '조교수'),
    (181, '경영경제대학', '경영학부', '조교수'),
    (182, '경영경제대학', '경영학부', '조교수'),
    (183, '경영경제대학', '경영학부', '조교수'),
    (184, '경영경제대학', '경영학부', '조교수'),
    (185, '경영경제대학', '경영학부', '조교수'),
    (186, '경영경제대학', '경영학부', '조교수'),
    (187, '경영경제대학', '경영학부', '조교수'),
    (188, '경영경제대학', '경영학부', '조교수'),
    (189, '경영경제대학', '경영학부', '조교수'),
    (190, '경영경제대학', '경제학과', '부교수'),
    (191, '경영경제대학', '경제학과', '교수'),
    (192, '경영경제대학', '경제학과', '교수'),
    (193, '경영경제대학', '경제학과', '부교수'),
    (194, '경영경제대학', '경제학과', '부교수'),
    (195, '경영경제대학', '경제학과', '부교수'),
    (196, '경영경제대학', '경제학과', '부교수'),
    (197, '경영경제대학', '경제학과', '부교수'),
    (198, '경영경제대학', '경제학과', '조교수'),
    (199, '경영경제대학', '경제학과', '조교수'),
    (200, '경영경제대학', '경제학과', '부교수'),
    (201, '경영경제대학', '경제학과', '조교수'),
    (202, '경영경제대학', '경제학과', '초빙교수'),
    (203, '경영경제대학', '경제학과', '초빙교수'),
    (204, '경영경제대학', '경제학과', '초빙교수'),
    (205, '인문과학대학', '국어국문학과', '교수'),
    (206, '인문과학대학', '국어국문학과', '부교수'),
    (207, '인문과학대학', '국어국문학과', '조교수'),
    (208, '인문과학대학', '국어국문학과', '초빙교수'),
    (209, '인문과학대학', '영어데이터융합전공', '교수'),
    (210, '인문과학대학', '영어데이터융합전공', '교수'),
    (211, '인문과학대학', '영어데이터융합전공', '교수'),
    (212, '인문과학대학', '영어데이터융합전공', '교수'),
    (213, '인문과학대학', '영어데이터융합전공', '부교수'),
    (214, '인문과학대학', '영어데이터융합전공', '조교수'),
    (215, '인문과학대학', '영어데이터융합전공', '명예교수'),
    (216, '인문과학대학', '영어데이터융합전공', '명예교수'),
    (217, '인문과학대학', '국제일본학전공', '교수'),
    (218, '인문과학대학', '국제일본학전공', '조교수'),
    (219, '인문과학대학', '국제일본학전공', '조교수'),
    (220, '인문과학대학', '국제일본학전공', '조교수'),
    (221, '인문과학대학', '중국통상학전공', '교수'),
    (222, '인문과학대학', '중국통상학전공', '교수'),
    (223, '인문과학대학', '중국통상학전공', '교수'),
    (224, '인문과학대학', '중국통상학전공', '교수'),
    (225, '인문과학대학', '중국통상학전공', '조교수'),
    (226, '인문과학대학', '중국통상학전공', '초빙교수'),
    (227, '인문과학대학', '역사학과', '부교수'),
    (228, '인문과학대학', '역사학과', '부교수'),
    (229, '인문과학대학', '역사학과', '부교수'),
    (230, '인문과학대학', '역사학과', '조교수'),
    (231, '인문과학대학', '교육학과', '교수'),
    (232, '인문과학대학', '교육학과', '교수'),
    (233, '인문과학대학', '교육학과', '교수'),
    (234, '인문과학대학', '교육학과', '부교수'),
    (235, '인문과학대학', '교육학과', '부교수'),
    (236, '인문과학대학', '교육학과', '조교수'),
    (237, '사회과학대학', '행정학과', '조교수'),
    (238, '사회과학대학', '행정학과', '교수'),
    (239, '사회과학대학', '행정학과', '교수'),
    (240, '사회과학대학', '행정학과', '교수'),
    (241, '사회과학대학', '행정학과', '부교수'),
    (242, '사회과학대학', '행정학과', '부교수'),
    (243, '사회과학대학', '행정학과', '부교수'),
    (244, '사회과학대학', '행정학과', '초빙교수'),
    (245, '사회과학대학', '미디어커뮤니케이션학과', '조교수'),
    (246, '사회과학대학', '미디어커뮤니케이션학과', '교수'),
    (247, '사회과학대학', '미디어커뮤니케이션학과', '교수'),
    (248, '사회과학대학', '미디어커뮤니케이션학과', '교수'),
    (249, '사회과학대학', '미디어커뮤니케이션학과', '교수'),
    (250, '사회과학대학', '미디어커뮤니케이션학과', '교수'),
    (251, '사회과학대학', '미디어커뮤니케이션학과', '부교수'),
    (252, '사회과학대학', '미디어커뮤니케이션학과', '조교수'),
    (253, '사회과학대학', '미디어커뮤니케이션학과', '부교수'),
    (254, '사회과학대학', '미디어커뮤니케이션학과', '초빙교수'),
    (255, '사회과학대학', '법학과', '교수'),
    (256, '사회과학대학', '법학과', '교수'),
    (257, '인공지능융합대학', '디자인이노베이션전공', '조교수'),
    (258, '인공지능융합대학', '디자인이노베이션전공', '교수'),
    (259, '인공지능융합대학', '디자인이노베이션전공', '부교수'),
    (260, '인공지능융합대학', '디자인이노베이션전공', '부교수'),
    (261, '인공지능융합대학', '디자인이노베이션전공', '조교수'),
    (262, '인공지능융합대학', '만화애니메이션텍전공', '조교수'),
    (263, '인공지능융합대학', '만화애니메이션텍전공', '교수'),
    (264, '인공지능융합대학', '만화애니메이션텍전공', '교수'),
    (265, '인공지능융합대학', '만화애니메이션텍전공', '교수'),
    (266, '인공지능융합대학', '만화애니메이션텍전공', '부교수'),
    (267, '인공지능융합대학', '만화애니메이션텍전공', '조교수'),
    (268, '인공지능융합대학', '만화애니메이션텍전공', '부교수'),
    (269, '인공지능융합대학', '만화애니메이션텍전공', '초빙교수'),
    (270, '인공지능융합대학', '만화애니메이션텍전공', '초빙교수'),
    (271, '인공지능융합대학', '만화애니메이션텍전공', '초빙교수'),
    (272, '인공지능융합대학', '만화애니메이션텍전공', '초빙교수'),
    (273, '호텔관광대학', '호텔관광경영학전공', '부교수'),
    (274, '호텔관광대학', '호텔관광경영학전공', '교수'),
    (275, '호텔관광대학', '호텔관광경영학전공', '교수'),
    (276, '호텔관광대학', '호텔관광경영학전공', '교수'),
    (277, '호텔관광대학', '호텔관광경영학전공', '교수'),
    (278, '호텔관광대학', '호텔관광경영학전공', '교수'),
    (279, '호텔관광대학', '호텔관광경영학전공', '교수'),
    (280, '호텔관광대학', '호텔관광경영학전공', '교수'),
    (281, '호텔관광대학', '호텔관광경영학전공', '교수'),
    (282, '호텔관광대학', '호텔관광경영학전공', '부교수'),
    (283, '호텔관광대학', '호텔관광경영학전공', '부교수'),
    (284, '호텔관광대학', '호텔관광경영학전공', '부교수'),
    (285, '호텔관광대학', '호텔관광경영학전공', '부교수'),
    (286, '호텔관광대학', '호텔관광경영학전공', '부교수'),
    (287, '호텔관광대학', '호텔관광경영학전공', '조교수'),
    (288, '호텔관광대학', '호텔관광경영학전공', '조교수'),
    (289, '호텔관광대학', '호텔관광경영학전공', '조교수'),
    (290, '호텔관광대학', '호텔관광경영학전공', '조교수'),
    (291, '호텔관광대학', '호텔관광경영학전공', '초빙교수'),
    (292, '호텔관광대학', '호텔관광경영학전공', '명예교수'),
    (293, '호텔관광대학', '호텔관광경영학전공', '명예교수'),
    (294, '호텔관광대학', '호텔관광경영학전공', '명예교수'),
    (295, '호텔관광대학', '외식경영학전공', '교수'),
    (296, '호텔관광대학', '외식경영학전공', '교수'),
    (297, '호텔관광대학', '외식경영학전공', '교수'),
    (298, '호텔관광대학', '외식경영학전공', '교수'),
    (299, '호텔관광대학', '외식경영학전공', '교수'),
    (300, '호텔관광대학', '외식경영학전공', '교수'),
    (301, '호텔관광대학', '외식경영학전공', '교수'),
    (302, '호텔관광대학', '조리서비스경영학과', '초빙교수'),
    (296, '호텔관광대학', '조리서비스경영학과', '교수'),
    (295, '호텔관광대학', '조리서비스경영학과', '교수'),
    (299, '호텔관광대학', '조리서비스경영학과', '교수'),
    (301, '호텔관광대학', '조리서비스경영학과', '교수'),
    (303, '호텔관광대학', '호텔외식관광프랜차이즈경영학과', '초빙교수'),
    (296, '호텔관광대학', '호텔외식관광프랜차이즈경영학과', '교수'),
    (297, '호텔관광대학', '호텔외식관광프랜차이즈경영학과', '교수'),
    (295, '호텔관광대학', '호텔외식관광프랜차이즈경영학과', '교수'),
    (298, '호텔관광대학', '호텔외식관광프랜차이즈경영학과', '교수'),
    (299, '호텔관광대학', '호텔외식관광프랜차이즈경영학과', '교수'),
    (301, '호텔관광대학', '호텔외식관광프랜차이즈경영학과', '교수'),
    (295, '호텔관광대학', '호텔외식비즈니스학과', '교수'),
    (296, '호텔관광대학', '호텔외식비즈니스학과', '교수'),
    (297, '호텔관광대학', '호텔외식비즈니스학과', '교수'),
    (299, '호텔관광대학', '호텔외식비즈니스학과', '교수'),
    (301, '호텔관광대학', '호텔외식비즈니스학과', '교수'),
    (302, '호텔관광대학', '호텔외식비즈니스학과', '초빙교수'),
    (1, '인공지능융합대학', 'AI융합전자공학과', '교수'),
    (2, '인공지능융합대학', 'AI융합전자공학과', '교수'),
    (3, '인공지능융합대학', 'AI융합전자공학과', '교수');

INSERT INTO college (name)
SELECT DISTINCT a.college_name FROM v44_catalog_affiliation a
WHERE NOT EXISTS (SELECT 1 FROM college c WHERE c.name = a.college_name);

INSERT INTO department (college_id, name)
SELECT DISTINCT c.id, a.department_name
FROM v44_catalog_affiliation a JOIN college c ON c.name = a.college_name
WHERE NOT EXISTS (SELECT 1 FROM department d WHERE d.college_id = c.id AND d.name = a.department_name);

UPDATE v44_catalog_source SET department_id = (
    SELECT d.id FROM department d JOIN college c ON c.id = d.college_id
    WHERE c.name = v44_catalog_source.college_name AND d.name = v44_catalog_source.department_name
);
UPDATE v44_catalog_professor SET department_id = (
    SELECT d.id FROM department d JOIN college c ON c.id = d.college_id
    WHERE c.name = v44_catalog_professor.college_name AND d.name = v44_catalog_professor.department_name
);
UPDATE v44_catalog_affiliation SET department_id = (
    SELECT d.id FROM department d JOIN college c ON c.id = d.college_id
    WHERE c.name = v44_catalog_affiliation.college_name AND d.name = v44_catalog_affiliation.department_name
);

INSERT INTO v44_catalog_guard
SELECT 'source department/parser mismatch', COUNT(*)
FROM v44_catalog_source s JOIN crawl_source existing ON existing.source_url = s.source_url
WHERE existing.department_id <> s.department_id OR existing.parser_type <> s.parser_type;

INSERT INTO v44_catalog_guard
SELECT 'same email, different professor name', COUNT(*)
FROM v44_catalog_professor s JOIN professor p ON p.email = s.email
WHERE CAST(p.name AS BINARY(400)) <> CAST(s.professor_name AS BINARY(400));

INSERT INTO v44_catalog_guard
SELECT 'same department/name, different or missing email', COUNT(*)
FROM v44_catalog_professor s JOIN professor p
    ON p.department_id = s.department_id AND p.name = s.professor_name
WHERE p.email <> s.email OR (p.email IS NULL AND s.email IS NOT NULL)
    OR (p.email IS NOT NULL AND s.email IS NULL);

INSERT INTO v44_catalog_guard
SELECT 'ambiguous NULL-email professor', COUNT(*) FROM v44_catalog_professor s
WHERE s.email IS NULL AND (SELECT COUNT(*) FROM professor p
    WHERE p.email IS NULL AND p.department_id = s.department_id AND p.name = s.professor_name) > 1;

UPDATE v44_catalog_professor SET professor_id = (
    SELECT p.id FROM professor p
    WHERE (v44_catalog_professor.email IS NOT NULL AND p.email = v44_catalog_professor.email)
       OR (v44_catalog_professor.email IS NULL AND p.email IS NULL
           AND p.department_id = v44_catalog_professor.department_id AND p.name = v44_catalog_professor.professor_name)
);

INSERT INTO v44_catalog_guard
SELECT 'ambiguous active laboratory', COUNT(*) FROM v44_catalog_professor s
WHERE (SELECT COUNT(*) FROM laboratory l WHERE l.professor_id = s.professor_id AND l.deleted_at IS NULL) > 1;

INSERT INTO v44_catalog_guard
SELECT 'existing professor has only deleted laboratories; do not resurrect', COUNT(*)
FROM v44_catalog_professor s
WHERE EXISTS (SELECT 1 FROM laboratory l WHERE l.professor_id = s.professor_id)
  AND NOT EXISTS (SELECT 1 FROM laboratory l WHERE l.professor_id = s.professor_id AND l.deleted_at IS NULL);

INSERT INTO v44_catalog_guard
SELECT 'laboratory name belongs to another professor', COUNT(*)
FROM v44_catalog_professor s JOIN laboratory l ON l.department_id = s.department_id
    AND l.name = s.laboratory_name AND l.deleted_at IS NULL
WHERE s.professor_id IS NULL OR l.professor_id <> s.professor_id;

-- All ambiguity checks precede canonical writes. Existing profiles are never overwritten.
INSERT INTO crawl_source (department_id, source_name, source_url, parser_type, version)
SELECT s.department_id, s.source_name, s.source_url, s.parser_type, 0 FROM v44_catalog_source s
WHERE NOT EXISTS (SELECT 1 FROM crawl_source existing WHERE existing.source_url = s.source_url);

INSERT INTO professor (department_id, name, email, position)
SELECT department_id, professor_name, email, position FROM v44_catalog_professor WHERE professor_id IS NULL;

UPDATE v44_catalog_professor SET professor_id = (
    SELECT p.id FROM professor p
    WHERE (v44_catalog_professor.email IS NOT NULL AND p.email = v44_catalog_professor.email)
       OR (v44_catalog_professor.email IS NULL AND p.email IS NULL
           AND p.department_id = v44_catalog_professor.department_id AND p.name = v44_catalog_professor.professor_name)
);

INSERT INTO laboratory (professor_id, department_id, name, website_url, description, recruitment_status, name_source)
SELECT s.professor_id, p.department_id, s.laboratory_name, s.website_url, s.description, 'UNKNOWN', 'GENERATED'
FROM v44_catalog_professor s JOIN professor p ON p.id = s.professor_id
WHERE NOT EXISTS (SELECT 1 FROM laboratory l WHERE l.professor_id = s.professor_id AND l.deleted_at IS NULL);

UPDATE v44_catalog_professor SET laboratory_id = (
    SELECT l.id FROM laboratory l WHERE l.professor_id = v44_catalog_professor.professor_id AND l.deleted_at IS NULL
);

INSERT INTO professor_department (professor_id, department_id, position)
SELECT s.professor_id, a.department_id, a.position
FROM v44_catalog_affiliation a JOIN v44_catalog_professor s ON s.record_key = a.record_key
WHERE NOT EXISTS (SELECT 1 FROM professor_department existing
    WHERE existing.professor_id = s.professor_id AND existing.department_id = a.department_id);

INSERT INTO laboratory_department (laboratory_id, department_id)
SELECT s.laboratory_id, a.department_id
FROM v44_catalog_affiliation a JOIN v44_catalog_professor s ON s.record_key = a.record_key
WHERE NOT EXISTS (SELECT 1 FROM laboratory_department existing
    WHERE existing.laboratory_id = s.laboratory_id AND existing.department_id = a.department_id);

INSERT INTO v44_catalog_guard
SELECT 'unresolved professor or laboratory', COUNT(*) FROM v44_catalog_professor
WHERE professor_id IS NULL OR laboratory_id IS NULL;

INSERT INTO v44_catalog_guard
SELECT 'missing professor affiliation', COUNT(*)
FROM v44_catalog_affiliation a JOIN v44_catalog_professor s ON s.record_key = a.record_key
WHERE NOT EXISTS (SELECT 1 FROM professor_department pd
    WHERE pd.professor_id = s.professor_id AND pd.department_id = a.department_id);

INSERT INTO v44_catalog_guard
SELECT 'missing laboratory affiliation', COUNT(*)
FROM v44_catalog_affiliation a JOIN v44_catalog_professor s ON s.record_key = a.record_key
WHERE NOT EXISTS (SELECT 1 FROM laboratory_department ld
    WHERE ld.laboratory_id = s.laboratory_id AND ld.department_id = a.department_id);

DROP TABLE v44_catalog_guard;
DROP TABLE v44_catalog_affiliation;
DROP TABLE v44_catalog_professor;
DROP TABLE v44_catalog_source;
